### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by ReadyTeresa** [Ricardokevins/Bert-In-Relation-Extraction#1]
提供的数据地址：https://ai.baidu.com/broad/download?dataset=dureader
但是这里下不了数据了
请问还有什么方法可以获取数据

**Comment by Ricardokevins** [comment]
我刚刚试了一下，还是可以下载的，打开网页即百度的数据集下载界面，左侧栏选择Knowledge Extraction，下载train和dev

**Comment by Ricardokevins** [comment]
> 提供的数据地址：https://ai.baidu.com/broad/download?dataset=dureader
> 但是这里下不了数据了
> 请问还有什么方法可以获取数据
我刚刚试了一下，还是可以下载的，打开网页即百度的数据集下载界面，左侧栏选择Knowledge Extraction，下载train和dev

**Comment by Ricardokevins** [comment]
> 提供的数据地址：https://ai.baidu.com/broad/download?dataset=dureader
> 但是这里下不了数据了
> 请问还有什么方法可以获取数据

我刚刚试了一下，还是可以下载的，打开网页即百度的数据集下载界面，左侧栏选择Knowledge Extraction，下载train和dev

**Comment by ReadyTeresa** [comment]
好的，感谢

**Comment by ReadyTeresa** [comment]
> > 提供的数据地址：https://ai.baidu.com/broad/download?dataset=dureader
> > 但是这里下不了数据了
> > 请问还有什么方法可以获取数据
> 
> 我刚刚试了一下，还是可以下载的，打开网页即百度的数据集下载界面，左侧栏选择Knowledge Extraction，下载train和dev
我下了数据，数据内容是词性标注的。

**Comment by Ricardokevins** [comment]
> > > 提供的数据地址：https://ai.baidu.com/broad/download?dataset=dureader
> > > 但是这里下不了数据了
> > > 请问还有什么方法可以获取数据
> > 
> > 
> > 我刚刚试了一下，还是可以下载的，打开网页即百度的数据集下载界面，左侧栏选择Knowledge Extraction，下载train和dev
> > 我下了数据，数据内容是词性标注的。

仔细完整的阅读一下数据

**Comment by ReadyTeresa** [comment]
> > > > 提供的数据地址：https://ai.baidu.com/broad/download?dataset=dureader
> > > > 但是这里下不了数据了
> > > > 请问还有什么方法可以获取数据
> > > 
> > > 
> > > 我刚刚试了一下，还是可以下载的，打开网页即百度的数据集下载界面，左侧栏选择Knowledge Extraction，下载train和dev
> > > 我下了数据，数据内容是词性标注的。
> 
> 仔细完整的阅读一下数据

额哦，发现了。
请问这个需要多大内存，我是45G，报out of Memory 问题
