### ISSUE TITLE
loader.py

### ISSUE THREAD

**Issue by ZMD177** [Ricardokevins/Bert-In-Relation-Extraction#10]
运行这个没反应
没得到dev.json

**Comment by Ricardokevins** [comment]
> 运行这个没反应 没得到dev.json

需要取消prepare_data函数的注释（第66行），因为我不想每次运行都要重新生成（又懒得整理代码）所以默认是被注释了

**Comment by Ricardokevins** [comment]
> 运行这个没反应 没得到dev.json

如果没有啥问题的话，我就close issue了。假如还有问题，或者新的问题，欢迎reopen issue，或者是开新的issue

**Comment by ZMD177** [comment]
好的 谢谢您



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 21, 2021 21:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Ricardokevins/Bert-In-Relation-Extraction] loader.py (Issue #10)




  
运行这个没反应 没得到dev.json
  
如果没有啥问题的话，我就close issue了。假如还有问题，或者新的问题，欢迎reopen issue，或者是开新的issue
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
