### ISSUE TITLE
训练过程不收敛

### ISSUE THREAD

**Issue by qq594495953** [Ricardokevins/Bert-In-Relation-Extraction#11]
你好，我在使用您的项目时，训练的结果不收敛，ACC一直在0.16左右，请问您之前有出现过这种情况吗

**Comment by Ricardokevins** [comment]
> 你好，我在使用您的项目时，训练的结果不收敛，ACC一直在0.16左右，请问您之前有出现过这种情况吗

没有，我推荐检查一下数据格式以及一些超参数的设定

**Comment by qq594495953** [comment]
> > 你好，我在使用您的项目时，训练的结果不收敛，ACC一直在0.16左右，请问您之前有出现过这种情况吗
> 
> 没有，我推荐检查一下数据格式以及一些超参数的设定

**Comment by qq594495953** [comment]
> > 你好，我在使用您的项目时，训练的结果不收敛，ACC一直在0.16左右，请问您之前有出现过这种情况吗
> 
> 没有，我推荐检查一下数据格式以及一些超参数的设定

**Comment by qq594495953** [comment]
额，我使用了你注释掉的Adamw优化器，模型没有收敛，换成SGD后收敛了，我想问下这是由于什么原因引起的呢？

**Comment by Ricardokevins** [comment]
> 额，我使用了你注释掉的Adamw优化器，模型没有收敛，换成SGD后收敛了，我想问下这是由于什么原因引起的呢？

可能和学习率大小的设置有一些关系吧，0.002可能对AdamW太大了？我不大确定，需要更多训练过程的信息以及实验来确定，你可以多试试
