### ISSUE TITLE
data

### ISSUE THREAD

**Issue by beitata** [Ricardokevins/Bert-In-Relation-Extraction#12]
大佬，您好，在github看了您的bert关系抽取项目，冒昧打扰您。您的训练数据和测试数据为什么都是用的一个呀？
那我要将这个模型用于抽取输入的文本，那也要把输入文本处理成train.json格式吗？

**Comment by Ricardokevins** [comment]
> 大佬，您好，在github看了您的bert关系抽取项目，冒昧打扰您。您的训练数据和测试数据为什么都是用的一个呀？ 那我要将这个模型用于抽取输入的文本，那也要把输入文本处理成train.json格式吗？

直接用于测试的可以参考一下demo.py里的写法，你要用这个来预测出实体间的关系吗？

**Comment by beitata** [comment]
> 

我想从输入文本里面抽取三元组。

**Comment by beitata** [comment]
> > 大佬，您好，在github看了您的bert关系抽取项目，冒昧打扰您。您的训练数据和测试数据为什么都是用的一个呀？ 那我要将这个模型用于抽取输入的文本，那也要把输入文本处理成train.json格式吗？
> 
> 直接用于测试的可以参考一下demo.py里的写法，你要用这个来预测出实体间的关系吗？

所以我得抽取实体间的关系。

**Comment by Ricardokevins** [comment]
> > > 大佬，您好，在github看了您的bert关系抽取项目，冒昧打扰您。您的训练数据和测试数据为什么都是用的一个呀？ 那我要将这个模型用于抽取输入的文本，那也要把输入文本处理成train.json格式吗？
> > 
> > 
> > 直接用于测试的可以参考一下demo.py里的写法，你要用这个来预测出实体间的关系吗？
> 
> 所以我得抽取实体间的

**Comment by Ricardokevins** [comment]
> > > 大佬，您好，在github看了您的bert关系抽取项目，冒昧打扰您。您的训练数据和测试数据为什么都是用的一个呀？ 那我要将这个模型用于抽取输入的文本，那也要把输入文本处理成train.json格式吗？
> > 
> > 
> > 直接用于测试的可以参考一下demo.py里的写法，你要用这个来预测出实体间的关系吗？
> 
> 所以我得抽取实体间的关系。

昂，因为我这个只是单纯的关系抽取，所以你要先找到实体，然后把数据集处理成类似的格式，具体的参考demo.py和load.py
