### ISSUE TITLE
data——model

### ISSUE THREAD

**Issue by Hou-jing** [Ricardokevins/Bert-In-Relation-Extraction#13]

**Comment by Hou-jing** [comment]
pretrain 的model链接，方便在公开下吗？

**Comment by Hou-jing** [comment]
百度网盘的链接失效了

**Comment by Ricardokevins** [comment]
> pretrain 的model链接，方便在公开下吗？

pretrain model用的就是bert-base-chinsese，这个应该不难获取吧，可以去huggingface model里找

**Comment by Ricardokevins** [comment]
> 

我刚刚去百度网盘看了一下，链接确实失效了。。。（分享的时候选的是永久。可恶的百度还是把他弄没了。。）挂到百度网盘的时候我就删了本地的模型。。。所以可能需要你去huggingface下载一下bert-base-chinese，或者我这里更新一个bert-base-chinese的链接。。。

**Comment by Ricardokevins** [comment]
> 百度网盘的链接失效了

我刚刚去百度网盘看了一下，链接确实失效了。。。（分享的时候选的是永久。可恶的百度还是把他弄没了。。）挂到百度网盘的时候我就删了本地的模型。。。所以可能需要你去huggingface下载一下bert-base-chinese，或者我这里更新一个bert-base-chinese的链接。。。

**Comment by Ricardokevins** [comment]
> 百度网盘的链接失效了

我更新了链接，之前清理网盘的时候误操作了

**Comment by Hou-jing** [comment]
我在hugging_face里下载到了bert-base-chinese的源码文件，谢谢大佬！

**Comment by Hou-jing** [comment]
请问，你的预训练过程大概时长是 多久呢？

**Comment by Ricardokevins** [comment]
> 请问，你的预训练过程大概时长是 多久呢？

我没有预训练啊hhh，我直接训练的，训练时间忘记了，完整版（95%正确率）是在一张V100-32G上训练的，速度还蛮快的吧。（你可以直接用我更新链接里的模型，可以不用重新训练）

**Comment by Ricardokevins** [comment]
> 我在hugging_face里下载到了bert-base-chinese的源码文件，谢谢大佬！

能给个Star就更好了QAQ（没啥问题我就close issue了）

**Comment by Hou-jing** [comment]
楼主，我在训练mode时，第一个epoch完成后，模型时会停止训练吗？我觉得应该不是的，但是我在检查代码时，没有发现错误，我在model完成第一个train epoch 后，等待了2个小时，一直没有epoch 2,请问，这是什么问题呢？
![image](https://user-images.githubusercontent.com/75936962/151178532-66819af7-3527-4df6-aa2a-ba9ab5bda34e.png)

**Comment by Ricardokevins** [comment]
> 楼主，我在训练mode时，第一个epoch完成后，模型时会停止训练吗？我觉得应该不是的，但是我在检查代码时，没有发现错误，我在model完成第一个train epoch 后，等待了2个小时，一直没有epoch 2,请问，这是什么问题呢？ ![image](https://user-images.githubusercontent.com/75936962/151178532-66819af7-3527-4df6-aa2a-ba9ab5bda34e.png)

把数据改小一点（方便测试），然后在各个函数的位置用print看看是卡在哪里了

**Comment by Hou-jing** [comment]
![image](https://user-images.githubusercontent.com/75936962/151498421-b226d98c-df93-4b94-ba4d-ee47a2f2878e.png)
楼主，请问您是否知道这种情况，怎么处理吗？训练的过程中，acc突变为0

**Comment by Ricardokevins** [comment]
> ![image](https://user-images.githubusercontent.com/75936962/151498421-b226d98c-df93-4b94-ba4d-ee47a2f2878e.png) 楼主，请问您是否知道这种情况，怎么处理吗？训练的过程中，acc突变为0

。。。我咋知道。。。以及这个issue close了。我都收不到你的消息。。。
你考虑降低学习率看看吧。。。
