### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by Tlntin** [Ricardokevins/Bert-In-Relation-Extraction#14]
79-83行有一些git合并冲突
```python
<<<<<<< HEAD
            outputs = net(indexed_tokens, mask=att_mask)
=======
            outputs = net(indexed_tokens, att_mask)
>>>>>>> 16d86b2eeb56099ab75c63f83bb2b572bcd172dd
```

**Comment by Ricardokevins** [comment]
> 79-83行有一些git合并冲突
> 
> ```python
> <<<<<<< HEAD
>             outputs = net(indexed_tokens, mask=att_mask)
> =======
>             outputs = net(indexed_tokens, att_mask)
> >>>>>>> 16d86b2eeb56099ab75c63f83bb2b572bcd172dd
> ```

啥意思？你要向我的仓库commit？

**Comment by Ricardokevins** [comment]
> 79-83行有一些git合并冲突
> 
> ```python
> <<<<<<< HEAD
>             outputs = net(indexed_tokens, mask=att_mask)
> =======
>             outputs = net(indexed_tokens, att_mask)
> >>>>>>> 16d86b2eeb56099ab75c63f83bb2b572bcd172dd
> ```

我手动修改了文件，已commit。谢谢指正
