### ISSUE TITLE
效果复现

### ISSUE THREAD

**Issue by JackMeiLong** [Ricardokevins/Bert-In-Relation-Extraction#15]
hi
拜读了你的代码，有几个问题烦请解答一下：
1、修正：后来在所有的数据上训练和测试，测试数据36w，测试数据4w，eval正确率95+%
源训练数据共17W左右，源测试数据2W左右，请问36W、4W是如何构建的？
2、id2rel={0: 'UNK', 1: '主演', 2: '歌手', 3: '简称', 4: '总部地点', 5: '导演', 
        6: '出生地', 7: '目', 8: '出生日期', 9: '占地面积', 10: '上映时间',
        11: '出版社', 12: '作者', 13: '号', 14: '父亲', 15: '毕业院校', 
        16: '成立日期', 17: '改编自', 18: '主持人', 19: '所属专辑', 
        20: '连载网站', 21: '作词', 22: '作曲', 23: '创始人', 24: '丈夫', 
        25: '妻子', 26: '朝代', 27: '民族', 28: '国籍', 29: '身高', 30: '出品公司', 
        31: '母亲', 32: '编剧', 33: '首都', 34: '面积', 35: '祖籍', 36: '嘉宾', 
        37: '字', 38: '海拔', 39: '注册资本', 40: '制片人', 41: '董事长', 42: '所在城市',
        43: '气候', 44: '人口数量', 45: '邮政编码', 46: '主角', 47: '官方语言', 48: '修业年限'}   
源数据schema有一个关系标签‘专业代码’，而id2rel却没有，是用“UNK”替换。
3、整个网络架构，ent1+ent2+sentence 组成新的sentence，取last_hidden_states 中‘[CLS]’处的表征信息，
再通过一个Linear Layer 输出，请问是否对bert fine-tune?
4、相同的网络结构并没达到你92%的效果，训练过程如下：
![image](https://user-images.githubusercontent.com/16250425/153968959-532fd441-bb6c-44d8-b816-7e01b83d9353.png)

**Comment by Ricardokevins** [comment]
> 

第一个问题：应该是笔误，完整的数据集是36w训练，4w测试？我记得是
第二个问题：这个关系映射我是在一开始的2W子集数据上确定的，可能没有你提到的那个关系，因此没有列入。至于Unk是为了泛化，毕竟后续的使用可能会有unk，所以我就加了一个。
第三个问题：那肯定是fine-tuing了。。。你真的看了我的代码了嘛。。。不fine-tuing那在训练啥，只训练最后的mlp吗
第四个问题：相同的网络结构是否使用了相同的优化器，以及数据处理，包括随机种子。据我的记忆里，优化器的选择以及超参数有一定的影响。

**Comment by Ricardokevins** [comment]
> hi 拜读了你的代码，有几个问题烦请解答一下： 1、修正：后来在所有的数据上训练和测试，测试数据36w，测试数据4w，eval正确率95+% 源训练数据共17W左右，源测试数据2W左右，请问36W、4W是如何构建的？ 2、id2rel={0: 'UNK', 1: '主演', 2: '歌手', 3: '简称', 4: '总部地点', 5: '导演', 6: '出生地', 7: '目', 8: '出生日期', 9: '占地面积', 10: '上映时间', 11: '出版社', 12: '作者', 13: '号', 14: '父亲', 15: '毕业院校', 16: '成立日期', 17: '改编自', 18: '主持人', 19: '所属专辑', 20: '连载网站', 21: '作词', 22: '作曲', 23: '创始人', 24: '丈夫', 25: '妻子', 26: '朝代', 27: '民族', 28: '国籍', 29: '身高', 30: '出品公司', 31: '母亲', 32: '编剧', 33: '首都', 34: '面积', 35: '祖籍', 36: '嘉宾', 37: '字', 38: '海拔', 39: '注册资本', 40: '制片人', 41: '董事长', 42: '所在城市', 43: '气候', 44: '人口数量', 45: '邮政编码', 46: '主角', 47: '官方语言', 48: '修业年限'} 源数据schema有一个关系标签‘专业代码’，而id2rel却没有，是用“UNK”替换。 3、整个网络架构，ent1+ent2+sentence 组成新的sentence，取last_hidden_states 中‘[CLS]’处的表征信息， 再通过一个Linear Layer 输出，请问是否对bert fine-tune? 4、相同的网络结构并没达到你92%的效果，训练过程如下： ![image](https://user-images.githubusercontent.com/16250425/153968959-532fd441-bb6c-44d8-b816-7e01b83d9353.png)

可能确实有一些错误，你可以核实一下我修正。
这个仓库也不是什么论文的开源仓库，纯粹是简单又好玩，分享一下
加上时间比较长，我不能保证能复现和readme里一样的结果（当时的项目也没有对我这个的结果有太高的要求）
