### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by beitata** [Ricardokevins/Bert-In-Relation-Extraction#16]
老师，为什么我用您的main训练出模型后，运行demo出错，AttributeError: 'NoneType' object has no attribute 'data'。

**Comment by Ricardokevins** [comment]
> 老师，为什么我用您的main训练出模型后，运行demo出错，AttributeError: 'NoneType' object has no attribute 'data'。

我需要更多的信息，比如是哪一行出现的这个错误

**Comment by beitata** [comment]
File "D:/meishan/get_triple/Bert-In-Relation-Extraction-main/demo.py", line 69, in test
    _, predicted = torch.max(logits.data, 1)

**Comment by Ricardokevins** [comment]
> File "D:/meishan/get_triple/Bert-In-Relation-Extraction-main/demo.py", line 69, in test _, predicted = torch.max(logit

> File "D:/meishan/get_triple/Bert-In-Relation-Extraction-main/demo.py", line 69, in test _, predicted = torch.max(logits.data, 1)

你可以检查一下outputs，理论上来说在demo阶段不提供label，模型会返回 【None，logits】（见model.py）

**Comment by goldeneave** [comment]
我也遇到这个问题 请问你解决了吗
