### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by setsaill** [Ricardokevins/Bert-In-Relation-Extraction#17]
您好 请问我为啥报这个错误呀
![Uploading mmexport1645277170516.png…]()

**Comment by Ricardokevins** [comment]
你的图片上传是不是有问题，我这里是看不到图片

**Comment by setsaill** [comment]
好的 我重传下
![Uploading mmexport1645277170516.png…]()

**Comment by setsaill** [comment]
[Uploading 1.pdf…]()

**Comment by setsaill** [comment]
我发了个pdf不知道您看得了吗

**Comment by Ricardokevins** [comment]
> 我发了个pdf不知道您看得了吗

<img width="903" alt="image" src="https://user-images.githubusercontent.com/43642508/155134048-fc45d526-9721-4bce-a0bc-00516b8013df.png">

**Comment by Ricardokevins** [comment]
> 我发了个pdf不知道您看得了吗

好像还是不行，你用邮件吧，我也不清楚为啥，我这里用了代理也看不了

**Comment by Ricardokevins** [comment]
> 我发了个pdf不知道您看得了吗

你可以使用我主页标注的邮箱地址和我进行联系，我可以看得到

**Comment by setsaill** [comment]
这是图片
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ricardokevins/Bert-In-Relation-Extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17)





 
Closed #17.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ricardokevins** [comment]
> 这是图片 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" ***@***.***&gt;; 发送时间:&nbsp;2022年2月23日(星期三) 晚上7:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) Closed #17. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我还是看不到图。。。你重新clone代码再试试吧，我昨天修复了一个BUG，可能可以解决你的问题

**Comment by setsaill** [comment]
好的好的&nbsp; 我试试 麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ricardokevins/Bert-In-Relation-Extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月24日(星期四) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17)





  
这是图片 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" @.&gt;; 发送时间:&nbsp;2022年2月23日(星期三) 晚上7:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) Closed #17. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我还是看不到图。。。你重新clone代码再试试吧，我昨天修复了一个BUG，可能可以解决你的问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by setsaill** [comment]
您好 ，我运行了main.py 报错OSError: Can't load 'MODEL_NAME'. Make sure that:


- 'MODEL_NAME' is a correct model identifier listed on 'https://huggingface.co/models'


- or 'MODEL_NAME' is the correct path to a directory containing a 'config.json' file


在网上没有找到解决方法，麻烦您有空帮我看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ricardokevins/Bert-In-Relation-Extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月24日(星期四) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17)





  
这是图片 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" @.&gt;; 发送时间:&nbsp;2022年2月23日(星期三) 晚上7:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) Closed #17. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我还是看不到图。。。你重新clone代码再试试吧，我昨天修复了一个BUG，可能可以解决你的问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ricardokevins** [comment]
> 您好 ，我运行了main.py 报错OSError: Can't load 'MODEL_NAME'. Make sure that: - 'MODEL_NAME' is a correct model identifier listed on 'https://huggingface.co/models' - or 'MODEL_NAME' is the correct path to a directory containing a 'config.json' file 在网上没有找到解决方法，麻烦您有空帮我看看
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" ***@***.***&gt;; 发送时间:&nbsp;2022年2月24日(星期四) 晚上7:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) 这是图片 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" @.&gt;; 发送时间:&nbsp;2022年2月23日(星期三) 晚上7:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) Closed #17. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt; 我还是看不到图。。。你重新clone代码再试试吧，我昨天修复了一个BUG，可能可以解决你的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

那是因为你预训练模型没下载全，应该要包括config.json，我建议你看看这个https://github.com/Ricardokevins/Bert-In-Relation-Extraction/issues/7

**Comment by setsaill** [comment]
您好，请问项目里那个main.py运行 报错OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
怎么解决呀


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ricardokevins/Bert-In-Relation-Extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17)





  
您好 ，我运行了main.py 报错OSError: Can't load 'MODEL_NAME'. Make sure that: - 'MODEL_NAME' is a correct model identifier listed on 'https://huggingface.co/models' - or 'MODEL_NAME' is the correct path to a directory containing a 'config.json' file 在网上没有找到解决方法，麻烦您有空帮我看看
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" @.&gt;; 发送时间:&nbsp;2022年2月24日(星期四) 晚上7:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) 这是图片 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" @.&gt;; 发送时间:&nbsp;2022年2月23日(星期三) 晚上7:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) Closed #17. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 我还是看不到图。。。你重新clone代码再试试吧，我昨天修复了一个BUG，可能可以解决你的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
那是因为你预训练模型没下载全，应该要包括config.json，我建议你看看这个#7
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ricardokevins** [comment]
> 您好，请问项目里那个main.py运行 报错OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 怎么解决呀
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" ***@***.***&gt;; 发送时间:&nbsp;2022年2月25日(星期五) 下午4:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) 您好 ，我运行了main.py 报错OSError: Can't load 'MODEL_NAME'. Make sure that: - 'MODEL_NAME' is a correct model identifier listed on 'https://huggingface.co/models' - or 'MODEL_NAME' is the correct path to a directory containing a 'config.json' file 在网上没有找到解决方法，麻烦您有空帮我看看 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" @.&gt;; 发送时间:&nbsp;2022年2月24日(星期四) 晚上7:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) 这是图片 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" @.&gt;; 发送时间:&nbsp;2022年2月23日(星期三) 晚上7:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 有问题 (Issue #17) Closed #17. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 我还是看不到图。。。你重新clone代码再试试吧，我昨天修复了一个BUG，可能可以解决你的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 那是因为你预训练模型没下载全，应该要包括config.json，我建议你看看这个#7 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你模型下载的有问题，如上描述，看看issue7
