### ISSUE TITLE
可以做预测吗？

### ISSUE THREAD

**Issue by zh7y** [Ricardokevins/Bert-In-Relation-Extraction#19]
您好，请问这个项目可以做预测任务吗？

**Comment by Ricardokevins** [comment]
> 您好，请问这个项目可以做预测任务吗？

你指的具体是什么意思，就是不训练直接预测吗，这个可以参考README里的说明

**Comment by zh7y** [comment]
就是用训练好的模型，在新的句子上（比如随便给一个句子）抽取实体和关系

> > 你好，这个项目可以做任务预测吗？
> 
> 你指的具体是什么英文，就是不训练直接预测吗，这个可以参考README里的说明

**Comment by zh7y** [comment]
就是用训练好的模型，在新的数据上预测关系



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月17日(周四) 晚上10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ricardokevins/Bert-In-Relation-Extraction] 可以做预测吗？ (Issue #19)




  
您好，请问这个项目可以做预测任务吗？
  
你指的具体是什么意思，就是不训练直接预测吗，这个可以参考README里的说明
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
