### ISSUE TITLE
调用demo的问题

### ISSUE THREAD

**Issue by huaxiaolu** [Ricardokevins/Bert-In-Relation-Extraction#2]
我在调用博主你上传的已训练文件进行测试时  出现了'BertConfig' object has no attribute 'return_dict'的问题 请问改怎么解决 ，我自己尝试了一下没有解决成功

**Comment by mangonihao** [comment]
我调用的时候也出错，但和你不一样 ModuleNotFoundError: No module named 'transformers.modeling_bert'

**Comment by mangonihao** [comment]
> 我在调用博主你上传的已训练文件进行测试时 出现了'BertConfig' object has no attribute 'return_dict'的问题 请问改怎么解决 ，我自己尝试了一下没有解决成功

**Comment by Xie-Minghui** [comment]
> 我在调用博主你上传的已训练文件进行测试时 出现了'BertConfig' object has no attribute 'return_dict'的问题 请问改怎么解决 ，我自己尝试了一下没有解决成功

我调用的时候也出错，但和你不一样 ModuleNotFoundError: No module named 'transformers.modeling_bert'

**Comment by huaxiaolu** [comment]
你的问题我也遇到过 mangonihao= 你试试把transformers的版本换成3.4 ，应该是版本过高导致的  我的问题我不知道怎么解决

**Comment by Ricardokevins** [comment]
> > 我在调用博主你上传的已训练文件进行测试时 出现了'BertConfig' object has no attribute 'return_dict'的问题 请问改怎么解决 ，我自己尝试了一下没有解决成功
> 
> 我调用的时候也出错，但和你不一样 ModuleNotFoundError: No module named 'transformers.modeling_bert'

对的，可能和Transformer的版本有关，这个库迭代的蛮快的，有一些接口不一样了，可以google或者baidu查看其他人的解决方案，若没有解决可以在issue里再说

**Comment by Ricardokevins** [comment]
> 你的问题我也遇到过 mangonihao= 你试试把transformers的版本换成3.4 ，应该是版本过高导致的 我的问题我不知道怎么解决



> 我在调用博主你上传的已训练文件进行测试时 出现了'BertConfig' object has no attribute 'return_dict'的问题 请问改怎么解决 ，我自己尝试了一下没有解决成功

这个好像和保存的位置之类的有关系，可以看看如下的链接尝试解决，如果没有解决，给出你的环境参数等信息https://www.reddit.com/r/LanguageTechnology/comments/iujz9r/loading_saved_ner_transformers_model_causes/
https://stackoverflow.com/questions/63939072/loading-saved-ner-transformers-model-causes-attributeerror

**Comment by huaxiaolu** [comment]
好像并没有解决 我的环境 pytorch 1.2 cpu 版本 python 3.6.12 transformers 3.4.0  话说怎么指定一个评论回复 博主，像你回复我那样，刚刚查了一下没找到

**Comment by Xie-Minghui** [comment]
博主，请问你训练的配置是什么，以及transformer的版本是什么

**Comment by Xie-Minghui** [comment]
> 你的问题我也遇到过 mangonihao= 你试试把transformers的版本换成3.4 ，应该是版本过高导致的 我的问题我不知道怎么解决

确实如此，然后就是你的那个问题。我也尝试了很久，不行

**Comment by Ricardokevins** [comment]
> > 你的问题我也遇到过 mangonihao= 你试试把transformers的版本换成3.4 ，应该是版本过高导致的 我的问题我不知道怎么解决
> 
> 确实如此，然后就是你的那个问题。我也尝试了很久，不行

等会，也就是说存在两个问题，一个是他的，一个是你的，都没有解决是吧，这个项目有一段时间了，我本地跑一下给你们回复

**Comment by Ricardokevins** [comment]
> 好像并没有解决 我的环境 pytorch 1.2 cpu 版本 python 3.6.12 transformers 3.4.0 话说怎么指定一个评论回复 博主，像你回复我那样，刚刚查了一下没找到

右上角三个点的图标点击，选择quote reply

**Comment by Ricardokevins** [comment]
> > > 你的问题我也遇到过 mangonihao= 你试试把transformers的版本换成3.4 ，应该是版本过高导致的 我的问题我不知道怎么解决
> > 
> > 
> > 确实如此，然后就是你的那个问题。我也尝试了很久，不行
> 
> 等会，也就是说存在两个问题，一个是他的，一个是你的，都没有解决是吧，这个项目有一段时间了，我本地跑一下给你们回复

我在服务器上测试了demo.py的使用
版本问题上，我的相关版本：transformers = 2.5.1 torch =1.5.1 具体怎么降级可以百度，大概是pip install transformers == 2.5.1
为了使用方便，我更新了demo.py的若干代码

**Comment by Ricardokevins** [comment]
> 好像并没有解决 我的环境 pytorch 1.2 cpu 版本 python 3.6.12 transformers 3.4.0 话说怎么指定一个评论回复 博主，像你回复我那样，刚刚查了一下没找到

我在服务器上测试了demo.py的使用
版本问题上，我的相关版本：transformers = 2.5.1 torch =1.5.1 具体怎么降级可以百度，大概是pip install transformers == 2.5.1
为了使用方便，我更新了demo.py的若干代码

**Comment by huaxiaolu** [comment]
我使用了一下你的新demo代码，然后降低了transformer版本，但是还是报同样的错误 。然后我看你调用的模型名字是0.9537394662921348.pth，但是百度网盘提供的名字是model.pth，请问这两个模型文件是同一个吗？ 然后mangonihao 之前那个问题已经解决了，他现在遇到的是和我一样的问题 。 还有 我的右上角三个点那怎么没有quote reply 可恶

**Comment by Ricardokevins** [comment]
> 我使用了一下你的新demo代码，然后降低了transformer版本，但是还是报同样的错误 。然后我看你调用的模型名字是0.9537394662921348.pth，但是百度网盘提供的名字是model.pth，请问这两个模型文件是同一个吗？ 然后mangonihao 之前那个问题已经解决了，他现在遇到的是和我一样的问题 。 还有 我的右上角三个点那怎么没有quote reply 可恶

return_dict的问题吗，模型是一样的，只不过我没改命名而已，数字代表的正确率，这个模型保存可见训练代码

**Comment by Xie-Minghui** [comment]
> > 我使用了一下你的新demo代码，然后降低了transformer版本，但是还是报同样的错误 。然后我看你调用的模型名字是0.9537394662921348.pth，但是百度网盘提供的名字是model.pth，请问这两个模型文件是同一个吗？ 然后mangonihao 之前那个问题已经解决了，他现在遇到的是和我一样的问题 。 还有 我的右上角三个点那怎么没有quote reply 可恶
> 
> return_dict的问题吗，模型是一样的，只不过我没改命名而已，数字代表的正确率，这个模型保存可见训练代码

现在就是return_dict的问题

**Comment by GCKt** [comment]
我想问一下，你跑的代码当中有dev.json吗

**Comment by huaxiaolu** [comment]
dev.json你跑那个loader.py文件的函数可以下载

**Comment by GCKt** [comment]
我跑了loader.py，但是没有看见，而且执行mian，还是报没有dev.json,你跑完，dev.json在哪里

**Comment by Ricardokevins** [comment]
> dev.json你跑那个loader.py文件的函数可以下载

不能下载，需要先去数据源下载train,dev,test,https://github.com/Ricardokevins/Bert-In-Relation-Extraction/issues/1

**Comment by huaxiaolu** [comment]
说错了 不是下载 是加载 哈哈 数据集的自己下载 dev.json好像是作者大大处理之后的数据

**Comment by GCKt** [comment]
没有，这个函数是？不太懂，哥们，能不能加个qq联系下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ricardokevins/Bert-In-Relation-Extraction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 中午11:19
收件人:&nbsp;"Ricardokevins/Bert-In-Relation-Extraction"<Bert-In-Relation-Extraction@noreply.github.com&gt;;
抄送:&nbsp;"斕光"<2227974246@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 调用demo的问题 (#2)





 
你调用load.dev函数没有 哥们

**Comment by Ricardokevins** [comment]
> 没有，这个函数是？不太懂，哥们，能不能加个qq联系下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月4日(星期四) 中午11:19 收件人:&nbsp;"Ricardokevins/Bert-In-Relation-Extraction"<Bert-In-Relation-Extraction@noreply.github.com&gt;; 抄送:&nbsp;"斕光"<2227974246@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 调用demo的问题 (#2) 你调用load.dev函数没有 哥们 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我更新了readme 重新阅读一下我更新后的readme以及我给你回复的issue链接

**Comment by GCKt** [comment]
好的，感谢感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ricardokevins/Bert-In-Relation-Extraction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 中午11:28
收件人:&nbsp;"Ricardokevins/Bert-In-Relation-Extraction"<Bert-In-Relation-Extraction@noreply.github.com&gt;;
抄送:&nbsp;"斕光"<2227974246@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 调用demo的问题 (#2)





  
没有，这个函数是？不太懂，哥们，能不能加个qq联系下
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ricardokevins/Bert-In-Relation-Extraction" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月4日(星期四) 中午11:19 收件人:&nbsp;"Ricardokevins/Bert-In-Relation-Extraction"<Bert-In-Relation-Extraction@noreply.github.com&gt;; 抄送:&nbsp;"斕光"<2227974246@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Ricardokevins/Bert-In-Relation-Extraction] 调用demo的问题 (#2) 你调用load.dev函数没有 哥们 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我更新了readme 重新阅读一下我更新后的readme以及我给你回复的issue链接

**Comment by Ricardokevins** [comment]
> > > 我使用了一下你的新demo代码，然后降低了transformer版本，但是还是报同样的错误 。然后我看你调用的模型名字是0.9537394662921348.pth，但是百度网盘提供的名字是model.pth，请问这两个模型文件是同一个吗？ 然后mangonihao 之前那个问题已经解决了，他现在遇到的是和我一样的问题 。 还有 我的右上角三个点那怎么没有quote reply 可恶
> > 
> > 
> > return_dict的问题吗，模型是一样的，只不过我没改命名而已，数字代表的正确率，这个模型保存可见训练代码
> 
> 现在就是return_dict的问题

可以试试重新训练，我用笔记本的环境是可以train的，但是demo也会有和你们一样的问题（之前我都是在服务器上跑的，昨天在服务器上也是可以的）

**Comment by huaxiaolu** [comment]
好的 我试试 谢谢啦

**Comment by Xie-Minghui** [comment]
> > > > 我使用了一下你的新demo代码，然后降低了transformer版本，但是还是报同样的错误 。然后我看你调用的模型名字是0.9537394662921348.pth，但是百度网盘提供的名字是model.pth，请问这两个模型文件是同一个吗？ 然后mangonihao 之前那个问题已经解决了，他现在遇到的是和我一样的问题 。 还有 我的右上角三个点那怎么没有quote reply 可恶
> > > 
> > > 
> > > return_dict的问题吗，模型是一样的，只不过我没改命名而已，数字代表的正确率，这个模型保存可见训练代码
> > 
> > 
> > 现在就是return_dict的问题
> 
> 可以试试重新训练，我用笔记本的环境是可以train的，但是demo也会有和你们一样的问题（之前我都是在服务器上跑的，昨天在服务器上也是可以的）

博主，请问你租的服务器是什么配置

**Comment by Ricardokevins** [comment]
> > > > > 我使用了一下你的新demo代码，然后降低了transformer版本，但是还是报同样的错误 。然后我看你调用的模型名字是0.9537394662921348.pth，但是百度网盘提供的名字是model.pth，请问这两个模型文件是同一个吗？ 然后mangonihao 之前那个问题已经解决了，他现在遇到的是和我一样的问题 。 还有 我的右上角三个点那怎么没有quote reply 可恶
> > > > 
> > > > 
> > > > return_dict的问题吗，模型是一样的，只不过我没改命名而已，数字代表的正确率，这个模型保存可见训练代码
> > > 
> > > 
> > > 现在就是return_dict的问题
> > 
> > 
> > 可以试试重新训练，我用笔记本的环境是可以train的，但是demo也会有和你们一样的问题（之前我都是在服务器上跑的，昨天在服务器上也是可以的）
> 
> 博主，请问你租的服务器是什么配置

不是租的，就是研究组和社团的服务器，4卡V100和两张1080Ti

**Comment by huaxiaolu** [comment]
训练的时候 出现Traceback (most recent call last):
  File "main.py", line 50, in <module>
    data=load_train()
  File "/home/hadoop/文档/RE_new/Bert-new-In-Relation-Extraction-main/loader.py", line 86, in load_train
    tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')
  File "/home/hadoop/anaconda3/envs/pytorch1/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1581, in from_pretrained
    raise EnvironmentError(msg)
OSError: Couldn't reach server at '{}' to download vocabulary files.
请问是不是我的服务器的网络有问题无法获得服务呢

**Comment by Ricardokevins** [comment]
> 训练的时候 出现Traceback (most recent call last):
> File "main.py", line 50, in
> data=load_train()
> File "/home/hadoop/文档/RE_new/Bert-new-In-Relation-Extraction-main/loader.py", line 86, in load_train
> tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')
> File "/home/hadoop/anaconda3/envs/pytorch1/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1581, in from_pretrained
> raise EnvironmentError(msg)
> OSError: Couldn't reach server at '{}' to download vocabulary files.
> 请问是不是我的服务器的网络有问题无法获得服务呢

是的，出现报错可以自己查询谷歌和百度进行解决

**Comment by GCKt** [comment]
> > > > 我使用了一下你的新demo代码，然后降低了transformer版本，但是还是报同样的错误 。然后我看你调用的模型名字是0.9537394662921348.pth，但是百度网盘提供的名字是model.pth，请问这两个模型文件是同一个吗？ 然后mangonihao 之前那个问题已经解决了，他现在遇到的是和我一样的问题 。 还有 我的右上角三个点那怎么没有quote reply 可恶
> > > 
> > > 
> > > return_dict的问题吗，模型是一样的，只不过我没改命名而已，数字代表的正确率，这个模型保存可见训练代码
> > 
> > 
> > 现在就是return_dict的问题
> 
> 可以试试重新训练，我用笔记本的环境是可以train的，但是demo也会有和你们一样的问题（之前我都是在服务器上跑的，昨天在服务器上也是可以的）

博主，这个不用GPU，用cpu可以训练成功吗

**Comment by GCKt** [comment]
> 好的 我试试 谢谢啦
兄弟，你训练成功了吗

**Comment by huaxiaolu** [comment]
> > 好的 我试试 谢谢啦
> > 兄弟，你训练成功了吗

没有 我在服务器训练报上面那个网络问题我没找到解决办法

**Comment by GCKt** [comment]
> > > 好的 我试试 谢谢啦
> > > 兄弟，你训练成功了吗
> 
> 没有 我在服务器训练报上面那个网络问题我没找到解决办法

我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？

**Comment by huaxiaolu** [comment]
> > > > 好的 我试试 谢谢啦
> > > > 兄弟，你训练成功了吗
> > 
> > 
> > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> 
> 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？

我的笔记本配置不够  哈哈

**Comment by GCKt** [comment]
> > > > > 好的 我试试 谢谢啦
> > > > > 兄弟，你训练成功了吗
> > > 
> > > 
> > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > 
> > 
> > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> 
> 我的笔记本配置不够 哈哈

我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗

**Comment by huaxiaolu** [comment]
> > > > > > 好的 我试试 谢谢啦
> > > > > > 兄弟，你训练成功了吗
> > > > 
> > > > 
> > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > 
> > > 
> > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > 
> > 
> > 我的笔记本配置不够 哈哈
> 
> 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗

没有 博主运行demo不也有点问题吗 我就没去尝试了

**Comment by GCKt** [comment]
> > > > > > > 好的 我试试 谢谢啦
> > > > > > > 兄弟，你训练成功了吗
> > > > > 
> > > > > 
> > > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > > 
> > > > 
> > > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > > 
> > > 
> > > 我的笔记本配置不够 哈哈
> > 
> > 
> > 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗
> 
> 没有 博主运行demo不也有点问题吗 我就没去尝试了

好，兄弟，弄好了保持沟通

**Comment by Ricardokevins** [comment]
> > > > > > 好的 我试试 谢谢啦
> > > > > > 兄弟，你训练成功了吗
> > > > 
> > > > 
> > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > 
> > > 
> > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > 
> > 
> > 我的笔记本配置不够 哈哈
> 
> 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗

改小batchsize，笔记本的显存很小，建议batchsize为2，4，8

**Comment by GCKt** [comment]
> > > > > > > 好的 我试试 谢谢啦
> > > > > > > 兄弟，你训练成功了吗
> > > > > 
> > > > > 
> > > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > > 
> > > > 
> > > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > > 
> > > 
> > > 我的笔记本配置不够 哈哈
> > 
> > 
> > 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗
> 
> 改小batchsize，笔记本的显存很小，建议batchsize为2，4，8

博主，今天上午改成2了，但好像还是跑不动，我检测他已经走到了main.py中的最后train函数，然后一直卡在这，没有走动，然后电脑很热，这是正常的是吗？

**Comment by Ricardokevins** [comment]
> > > > > > > > 好的 我试试 谢谢啦
> > > > > > > > 兄弟，你训练成功了吗
> > > > > > 
> > > > > > 
> > > > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > > > 
> > > > > 
> > > > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > > > 
> > > > 
> > > > 我的笔记本配置不够 哈哈
> > > 
> > > 
> > > 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗
> > 
> > 
> > 改小batchsize，笔记本的显存很小，建议batchsize为2，4，8
> 
> 博主，今天上午改成2了，但好像还是跑不动，我检测他已经走到了main.py中的最后train函数，然后一直卡在这，没有走动，然后电脑很热，这是正常的是吗？

因为数据很大，38w，batchsize=2，笔记本的GPU又很慢，会跑非常非常久，建议把训练数据减小到2000

**Comment by GCKt** [comment]
> > > > > > > > > 好的 我试试 谢谢啦
> > > > > > > > > 兄弟，你训练成功了吗
> > > > > > > 
> > > > > > > 
> > > > > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > > > > 
> > > > > > 
> > > > > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > > > > 
> > > > > 
> > > > > 我的笔记本配置不够 哈哈
> > > > 
> > > > 
> > > > 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗
> > > 
> > > 
> > > 改小batchsize，笔记本的显存很小，建议batchsize为2，4，8
> > 
> > 
> > 博主，今天上午改成2了，但好像还是跑不动，我检测他已经走到了main.py中的最后train函数，然后一直卡在这，没有走动，然后电脑很热，这是正常的是吗？
> 
> 因为数据很大，38w，batchsize=2，笔记本的GPU又很慢，会跑非常非常久，建议把训练数据减小到2000

这个我改了，我把生成的train.json中的数据减小到300了

**Comment by GCKt** [comment]
> > > > > > > > > 好的 我试试 谢谢啦
> > > > > > > > > 兄弟，你训练成功了吗
> > > > > > > 
> > > > > > > 
> > > > > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > > > > 
> > > > > > 
> > > > > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > > > > 
> > > > > 
> > > > > 我的笔记本配置不够 哈哈
> > > > 
> > > > 
> > > > 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗
> > > 
> > > 
> > > 改小batchsize，笔记本的显存很小，建议batchsize为2，4，8
> > 
> > 
> > 博主，今天上午改成2了，但好像还是跑不动，我检测他已经走到了main.py中的最后train函数，然后一直卡在这，没有走动，然后电脑很热，这是正常的是吗？
> 
> 因为数据很大，38w，batchsize=2，笔记本的GPU又很慢，会跑非常非常久，建议把训练数据减小到2000

博主，我想问问，如果改成CPU，然后处理数据少一些，笔记本运行会快些吗？

**Comment by Ricardokevins** [comment]
> > > > > > > > > > 好的 我试试 谢谢啦
> > > > > > > > > > 兄弟，你训练成功了吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > > > > > 
> > > > > > > 
> > > > > > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > > > > > 
> > > > > > 
> > > > > > 我的笔记本配置不够 哈哈
> > > > > 
> > > > > 
> > > > > 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗
> > > > 
> > > > 
> > > > 改小batchsize，笔记本的显存很小，建议batchsize为2，4，8
> > > 
> > > 
> > > 博主，今天上午改成2了，但好像还是跑不动，我检测他已经走到了main.py中的最后train函数，然后一直卡在这，没有走动，然后电脑很热，这是正常的是吗？
> > 
> > 
> > 因为数据很大，38w，batchsize=2，笔记本的GPU又很慢，会跑非常非常久，建议把训练数据减小到2000
> 
> 这个我改了，我把生成的train.json中的数据减小到300了

你确认一下训练的主循环有没有在循环不就行了。。

**Comment by GCKt** [comment]
> > > > > > > > > > > 好的 我试试 谢谢啦
> > > > > > > > > > > 兄弟，你训练成功了吗
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 没有 我在服务器训练报上面那个网络问题我没找到解决办法
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我想问下，是直接在笔记本上训练是跑不动的，必须得用服务器吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 我的笔记本配置不够 哈哈
> > > > > > 
> > > > > > 
> > > > > > 我也不够，但搞不到服务器，我上午用GPU根本跑不动，我把数据集都减小很多，也不行，我现在试试改成cpu行不行，兄弟，你demo运行成功了吗
> > > > > 
> > > > > 
> > > > > 改小batchsize，笔记本的显存很小，建议batchsize为2，4，8
> > > > 
> > > > 
> > > > 博主，今天上午改成2了，但好像还是跑不动，我检测他已经走到了main.py中的最后train函数，然后一直卡在这，没有走动，然后电脑很热，这是正常的是吗？
> > > 
> > > 
> > > 因为数据很大，38w，batchsize=2，笔记本的GPU又很慢，会跑非常非常久，建议把训练数据减小到2000
> > 
> > 
> > 这个我改了，我把生成的train.json中的数据减小到300了
> 
> 你确认一下训练的主循环有没有在循环不就行了。。

好的，谢谢博主，我试试

**Comment by huaxiaolu** [comment]
由于服务器无法下载vocab 文件 ，即#tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')无法运行，我下载到本地之后在通过
temp = 'bert-base-chinese-vocab.txt'
   tokenizer = BertTokenizer.from_pretrained(temp)进行调用，但是报了
Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated，好像是方法过期了 ，这可咋办，博主知道其他的调用方法吗 我也还在查

**Comment by Ricardokevins** [comment]
> 由于服务器无法下载vocab 文件 ，即#tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')无法运行，我下载到本地之后在通过
> temp = 'bert-base-chinese-vocab.txt'
> tokenizer = BertTokenizer.from_pretrained(temp)进行调用，但是报了
> Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated，好像是方法过期了 ，这可咋办，博主知道其他的调用方法吗 我也还在查

不是很清楚。。。我这几天稍微有空一些，我看看

**Comment by huaxiaolu** [comment]
博主 新年好  请问我问的那个问题能解决吗  或者其他几个老哥问题解决了嘛

**Comment by Ricardokevins** [comment]
> 博主 新年好 请问我问的那个问题能解决吗 或者其他几个老哥问题解决了嘛

最近我找时间重构一下这个项目，写的有点乱，我找找时间QAQ

**Comment by Ricardokevins** [comment]
> 训练的时候 出现Traceback (most recent call last):
> File "main.py", line 50, in
> data=load_train()
> File "/home/hadoop/文档/RE_new/Bert-new-In-Relation-Extraction-main/loader.py", line 86, in load_train
> tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')
> File "/home/hadoop/anaconda3/envs/pytorch1/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1581, in from_pretrained
> raise EnvironmentError(msg)
> OSError: Couldn't reach server at '{}' to download vocabulary files.
> 请问是不是我的服务器的网络有问题无法获得服务呢

哦这个问题我知道了，需要去下载BERT对应的预训练模型的词表文件，改名为vocab.txt，然后修改加载的目录选择加载本地的就行（当然，网络好的可以直接下载，词表只有几百kb）
