### ISSUE TITLE
Demo问题

### ISSUE THREAD

**Issue by Claymoreeeee** [Ricardokevins/Bert-In-Relation-Extraction#20]
博主你好，我在运行完main.py之后原文件夹有了一个新的pth文件，名字是一串数字。然后运行demo.py的时候会报出
E   FileNotFoundError: [Errno 2] No such file or directory: './bert-base-chinese/test.pth'
但是bert-base-chinese文件夹里就只有vocab.txt  pytorch_model.bin 和 config.json三个文件哇，请问这是哪里出错了吗

**Comment by Ricardokevins** [comment]
> 

名字是数字，是因为我在main（训练）里会以Acc作为保存的模型的名字，所以是一串数字。
你是在自己的数据上训练了嘛。
你需要在demo.py里修改要加载的模型，即找到报错的代码位置，然后修改加载的路径

**Comment by Claymoreeeee** [comment]
没有用自己的数据训练，就是按照readme里面把数据和预处理弄好之后先运行了main，运行完成之后就直接运行demo了诶

**Comment by Ricardokevins** [comment]
> 没有用自己的数据训练，就是按照readme里面把数据和预处理弄好之后先运行了main，运行完成之后就直接运行demo了诶

那是因为我传了一个train.json作为示例数据，所以你运行main相当于是训练了。假如你要训练，建议处理自己的数据。
假如没有训练数据，那建议下载我提供的训练后的模型。
因为train.json比较小

**Comment by Claymoreeeee** [comment]
原本的那个train.json我好像是把它先删了，然后运行loader之后得到了两个新的train.json和dev.json然后再运行main.py的。如果用博主训练后的model.pth的话，是把它放在bert-base-chinese文件夹然后把demo里面原本test.pth的路径改成model的嘛

**Comment by Ricardokevins** [comment]
> 原本的那个train.json我好像是把它先删了，然后运行loader之后得到了两个新的train.json和dev.json然后再运行main.py的。如果用博主训练后的model.pth的话，是把它放在bert-base-chinese文件夹然后把demo里面原本test.pth的路径改成model的嘛

是这样的
