### ISSUE TITLE
调用训练后model的问题

### ISSUE THREAD

**Issue by Claymoreeeee** [Ricardokevins/Bert-In-Relation-Extraction#21]
博主你好，在弄好数据和预处理之后我尝试自己用main.py训练（train的训练次数调成了3次）然后调用demo.py输出成功了，但应该是因为训练不够的原因（三次训练最后一次产生的用acc当文件名的文件acc有0.6799) , 所以在demo.py输出的正确率比较低（如图）
![123123](https://user-images.githubusercontent.com/87629940/161371481-7af07af4-797a-4a23-b0df-9d838a8735aa.png)，所以我下载了博主给的训练之后的model.pth，然后把它放在了bert-base-chinere文件夹下（和main.py生成test.pth同一个文件夹） ， 然后在demo.py的test函数中把路径最后的test.pth改成了model.pth，但是运行的时候就会有报错了，报的错是

ModuleNotFoundError: No module named 'transformers.modeling_bert'

请问这是什么原因呢？谢谢

**Comment by Ricardokevins** [comment]
> 博主你好，在弄好数据和预处理之后我尝试自己用main.py训练（train的训练次数调成了3次）然后调用demo.py输出成功了，但应该是因为训练不够的原因（三次训练最后一次产生的用acc当文件名的文件acc有0.6799) , 所以在demo.py输出的正确率比较低（如图） ![123123](https://user-images.githubusercontent.com/87629940/161371481-7af07af4-797a-4a23-b0df-9d838a8735aa.png)，所以我下载了博主给的训练之后的model.pth，然后把它放在了bert-base-chinere文件夹下（和main.py生成test.pth同一个文件夹） ， 然后在demo.py的test函数中把路径最后的test.pth改成了model.pth，但是运行的时候就会有报错了，报的错是
> 
> ModuleNotFoundError: No module named 'transformers.modeling_bert'
> 
> 请问这是什么原因呢？谢谢

确认transformer的版本和README一致了吗

**Comment by Claymoreeeee** [comment]
版本好像是更高的版本，我降低一下版本再试试，谢谢博主

**Comment by Claymoreeeee** [comment]
> > 博主你好，在弄好数据和预处理之后我尝试自己用main.py训练（train的训练次数调成了3次）然后调用demo.py输出成功了，但应该是因为训练不够的原因（三次训练最后一次产生的用acc当文件名的文件acc有0.6799) , 所以在demo.py输出的正确率比较低（如图） ![123123](https://user-images.githubusercontent.com/87629940/161371481-7af07af4-797a-4a23-b0df-9d838a8735aa.png)，所以我下载了博主给的训练之后的model.pth，然后把它放在了bert-base-chinere文件夹下（和main.py生成test.pth同一个文件夹） ， 然后在demo.py的test函数中把路径最后的test.pth改成了model.pth，但是运行的时候就会有报错了，报的错是
> > ModuleNotFoundError: No module named 'transformers.modeling_bert'
> > 请问这是什么原因呢？谢谢
> 
> 确认transformer的版本和README一致了吗

问题解决啦，非常感谢博主，现在之前生成的test.pth不能用了应该是因为之前运行的时候transformer版本和现在的不一样了吧，再重新运行main.py生成一个现在版本的就行了哇。
