### ISSUE TITLE
请问 能从一句话中发现新的关系吗？

### ISSUE THREAD

**Issue by ll21121** [Ricardokevins/Bert-In-Relation-Extraction#22]
你好，我是新手，想问下这个问题
比如 我的老家在东北 ，  
我  家乡 东北
比如  我的XX在东北
新的关系词 如何发现呢？
id2rel 这里的关系是怎么得到的？

**Comment by Ricardokevins** [comment]
> 你好，我是新手，想问下这个问题 比如 我的老家在东北 ， 我 家乡 东北 比如 我的XX在东北 新的关系词 如何发现呢？ id2rel 这里的关系是怎么得到的？

不能，受限于模型训练的数据集，id2rel是我使用的数据集里已经预定义好的一些关系。并不是说从无到有自己发掘的。我更多的是你告诉模型有哪一些关系，然后模型在你给的选项里选一个。
你要用新的关系，就需要新的数据
