### ISSUE TITLE
没有测试集test

### ISSUE THREAD

**Issue by GiveMeAnApple99** [Ricardokevins/Bert-In-Relation-Extraction#23]
请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？

**Comment by Ricardokevins** [comment]
> 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？

为啥要看test.py?你只要看main和demo就行

**Comment by Ricardokevins** [comment]
> 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？

哪个只是测试用的，你当然可以自己选择读取测试集。而我report的结果是在main里用dev set得到的结果

**Comment by Ricardokevins** [comment]
> 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？

Test是不能使用train.json来做的，我只不过随便读取了一个。。。

**Comment by Ricardokevins** [comment]
> > 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？
> 
> 哪个只是测试用的，你当然可以自己选择读取测试集。而我report的结果是在main里用dev set得到的结果

原始数据就没有测试集，只有train和dev，我在train上训练，dev上测试并保存最好的Model，并报告dev上的结果，具体可以看README

**Comment by GiveMeAnApple99** [comment]
> > 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？
> 
> Test是不能使用train.json来做的，我只不过随便读取了一个。。。

看到了，demo.py的113行写的也是train.json；用的时候需要调整成自己的test.txt

**Comment by Ricardokevins** [comment]
> > > 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？
> > 
> > 
> > Test是不能使用train.json来做的，我只不过随便读取了一个。。。
> 
> 看到了，demo.py的113行写的也是train.json；用的时候需要调整成自己的test.txt

是的吧，很多代码是后来补上的，那个时候没有dev数据了，我懒得处理，直接读取了小的样例train.json，具体的你可以自己改一下

**Comment by Ricardokevins** [comment]
loader里读取的还是dev data

**Comment by GiveMeAnApple99** [comment]
> > > > 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？
> > > 
> > > 
> > > Test是不能使用train.json来做的，我只不过随便读取了一个。。。
> > 
> > 
> > 看到了，demo.py的113行写的也是train.json；用的时候需要调整成自己的test.txt
> 
> 是的吧，很多代码是后来补上的，那个时候没有dev数据了，我懒得处理，直接读取了小的样例train.json，具体的你可以自己改一下

🤣试着改下，谢谢

**Comment by Ricardokevins** [comment]
> > > > > 请问是没有测试集吗？只有训练集、验证集，test.py的111行是读取train.json训练集来做测试的？
> > > > 
> > > > 
> > > > Test是不能使用train.json来做的，我只不过随便读取了一个。。。
> > > 
> > > 
> > > 看到了，demo.py的113行写的也是train.json；用的时候需要调整成自己的test.txt
> > 
> > 
> > 是的吧，很多代码是后来补上的，那个时候没有dev数据了，我懒得处理，直接读取了小的样例train.json，具体的你可以自己改一下
> 
> 🤣试着改下，谢谢

没事，假如代码有帮助，给个Star嗷~
