### ISSUE TITLE
关于main.py 输出的疑问

### ISSUE THREAD

**Issue by kol66** [Ricardokevins/Bert-In-Relation-Extraction#25]
![image](https://user-images.githubusercontent.com/97020095/165717147-6d457035-3061-427a-9cd1-56dd981ec984.png)
请问运行main.py时，一开始下载的这两个是什么呢？预训练模型和字典吗？

**Comment by Ricardokevins** [comment]
> ![image](https://user-images.githubusercontent.com/97020095/165717147-6d457035-3061-427a-9cd1-56dd981ec984.png) 请问运行main.py时，一开始下载的这两个是什么呢？预训练模型和字典吗？

是

**Comment by Ricardokevins** [comment]
你需要指定读取位置

**Comment by lty-kali** [comment]
你好，可以详细说一下代码的流程吗？，比如一些函数的作用

**Comment by Ricardokevins** [comment]
> 你好，可以详细说一下代码的流程吗？，比如一些函数的作用

可以自己读代码吗，函数作用可以看函数名
