### ISSUE TITLE
main函数功能

### ISSUE THREAD

**Issue by lty-kali** [Ricardokevins/Bert-In-Relation-Extraction#27]
运行main得到的是一个训练过的模型吗？

**Comment by Ricardokevins** [comment]
https://github.com/Ricardokevins/Bert-In-Relation-Extraction/blob/main/README.md

**Comment by Ricardokevins** [comment]
> 运行main得到的是一个训练过的模型吗？

main文件一共就200行，你能不能读一读啊。再不济读一读README也行啊

**Comment by lty-kali** [comment]
>_< 真的看了，但是这个不太懂，并得到Fine-Tuing后的BERT

**Comment by Ricardokevins** [comment]
> > _< 真的看了，但是这个不太懂，并得到Fine-Tuing后的BERT
。。。这个python文件看不懂，你可能需要补充python基本语法和简单深度学习代码例子。。。这也不是我能够帮助你的。。。我一行一行代码的给你讲也不现实

**Comment by lty-kali** [comment]
main函数中train(net,dataset,num_epochs, learning_rate,  batch_size)其中num_epochs, learning_rate,  batch_size参数分别设置为1,0.002,4是怎么找到的，还有改进空间吗。

**Comment by Ricardokevins** [comment]
> main函数中train(net,dataset,num_epochs, learning_rate, batch_size)其中num_epochs, learning_rate, batch_size参数分别设置为1,0.002,4是怎么找到的，还有改进空间吗。

随便找的，你可以试试

**Comment by lty-kali** [comment]
你好，我发现test.py的功能好像在demo.py中都有改进，那么相对恶言test.py是不是没有什么作用了

**Comment by Ricardokevins** [comment]
> 你好，我发现test.py的功能好像在demo.py中都有改进，那么相对恶言test.py是不是没有什么作用了

你自己看看呗。。。
