### ISSUE TITLE
您好，关于运行mian的问题，已star，望解答，谢谢！

### ISSUE THREAD

**Issue by cantianaishu** [Ricardokevins/Bert-In-Relation-Extraction#29]
您好，我刚接触深度学习不久，所以问题比较简单，希望您别介意。

**问题一：**

我遵循了您readme中的步骤，现在正在运行main.py，但是一直卡在epoch 0 loss 就不往下进行了，运行过程如下所示
---Regenerate Data---
49
{0: 'UNK', 1: '主演', 2: '歌手', 3: '简称', 4: '总部地点', 5: '导演', 6: '出生地', 7: '目', 8: '出生日期', 9: '占地面积', 10: '上映时间', 11: '出版社', 12: '作者', 13: '号', 14: '父亲', 15: '毕业院校', 16: '成立日期', 17: '改编自', 18: '主持人', 19: '所属专辑', 20: '连载网站', 21: '作词', 22: '作曲', 23: '创始人', 24: '丈夫', 25: '妻子', 26: '朝代', 27: '民族', 28: '国籍', 29: '身高', 30: '出品公司', 31: '母亲', 32: '编剧', 33: '首都', 34: '面积', 35: '祖籍', 36: '嘉宾', 37: '字', 38: '海拔', 39: '注册资本', 40: '制片人', 41: '董事长', 42: '所在城市', 43: '气候', 44: '人口数量', 45: '邮政编码', 46: '主角', 47: '官方语言', 48: '修业年限'}
Some weights of the model checkpoint at ./bert-base-chinese were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
--train data--
torch.Size([200, 1, 128])
torch.Size([200, 1, 128])
torch.Size([200])
--train data--
torch.Size([200, 1, 128])
torch.Size([200, 1, 128])
torch.Size([200])
--eval data--
torch.Size([45558, 1, 128])
torch.Size([45558, 1, 128])
torch.Size([45558])
epoch  0  loss:  2.12479829788208 right 51 total 200 Acc: 0.255

**问题二：**
另外，请问一下，看了您的readme，如果能够跑通，或者直接使用您的模型，修改test，然后运行demo，就可以了吧？

**Comment by Ricardokevins** [comment]
> 您好，我刚接触深度学习不久，所以问题比较简单，希望您别介意。
> 
> **问题一：**
> 
> 我遵循了您readme中的步骤，现在正在运行main.py，但是一直卡在epoch 0 loss 就不往下进行了，运行过程如下所示 ---Regenerate Data--- 49 {0: 'UNK', 1: '主演', 2: '歌手', 3: '简称', 4: '总部地点', 5: '导演', 6: '出生地', 7: '目', 8: '出生日期', 9: '占地面积', 10: '上映时间', 11: '出版社', 12: '作者', 13: '号', 14: '父亲', 15: '毕业院校', 16: '成立日期', 17: '改编自', 18: '主持人', 19: '所属专辑', 20: '连载网站', 21: '作词', 22: '作曲', 23: '创始人', 24: '丈夫', 25: '妻子', 26: '朝代', 27: '民族', 28: '国籍', 29: '身高', 30: '出品公司', 31: '母亲', 32: '编剧', 33: '首都', 34: '面积', 35: '祖籍', 36: '嘉宾', 37: '字', 38: '海拔', 39: '注册资本', 40: '制片人', 41: '董事长', 42: '所在城市', 43: '气候', 44: '人口数量', 45: '邮政编码', 46: '主角', 47: '官方语言', 48: '修业年限'} Some weights of the model checkpoint at ./bert-base-chinese were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
> 
> * This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> * This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
>   --train data--
>   torch.Size([200, 1, 128])
>   torch.Size([200, 1, 128])
>   torch.Size([200])
>   --train data--
>   torch.Size([200, 1, 128])
>   torch.Size([200, 1, 128])
>   torch.Size([200])
>   --eval data--
>   torch.Size([45558, 1, 128])
>   torch.Size([45558, 1, 128])
>   torch.Size([45558])
>   epoch  0  loss:  2.12479829788208 right 51 total 200 Acc: 0.255
> 
> **问题二：** 另外，请问一下，看了您的readme，如果能够跑通，或者直接使用您的模型，修改test，然后运行demo，就可以了吧？

对于问题1：可能是因为在跑dev函数，所以看起来卡住了？你可以通过print大法看看”卡“在哪里了
对于问题2：似乎这样子的，当然要和你具体怎么用，读入什么数据有关。另外我附上的例子数据非常小，只是测试和做例子用的，并不是我原来使用的训练数据，如何获取这个数据可以见README。或者加载我发布的参数。否则大概率无法复现结果

**Comment by Ricardokevins** [comment]
> 您好，我刚接触深度学习不久，所以问题比较简单，希望您别介意。
> 
> **问题一：**
> 
> 我遵循了您readme中的步骤，现在正在运行main.py，但是一直卡在epoch 0 loss 就不往下进行了，运行过程如下所示 ---Regenerate Data--- 49 {0: 'UNK', 1: '主演', 2: '歌手', 3: '简称', 4: '总部地点', 5: '导演', 6: '出生地', 7: '目', 8: '出生日期', 9: '占地面积', 10: '上映时间', 11: '出版社', 12: '作者', 13: '号', 14: '父亲', 15: '毕业院校', 16: '成立日期', 17: '改编自', 18: '主持人', 19: '所属专辑', 20: '连载网站', 21: '作词', 22: '作曲', 23: '创始人', 24: '丈夫', 25: '妻子', 26: '朝代', 27: '民族', 28: '国籍', 29: '身高', 30: '出品公司', 31: '母亲', 32: '编剧', 33: '首都', 34: '面积', 35: '祖籍', 36: '嘉宾', 37: '字', 38: '海拔', 39: '注册资本', 40: '制片人', 41: '董事长', 42: '所在城市', 43: '气候', 44: '人口数量', 45: '邮政编码', 46: '主角', 47: '官方语言', 48: '修业年限'} Some weights of the model checkpoint at ./bert-base-chinese were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
> 
> * This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> * This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
>   --train data--
>   torch.Size([200, 1, 128])
>   torch.Size([200, 1, 128])
>   torch.Size([200])
>   --train data--
>   torch.Size([200, 1, 128])
>   torch.Size([200, 1, 128])
>   torch.Size([200])
>   --eval data--
>   torch.Size([45558, 1, 128])
>   torch.Size([45558, 1, 128])
>   torch.Size([45558])
>   epoch  0  loss:  2.12479829788208 right 51 total 200 Acc: 0.255
> 
> **问题二：** 另外，请问一下，看了您的readme，如果能够跑通，或者直接使用您的模型，修改test，然后运行demo，就可以了吧？

哦，我猜到是为啥了，因为你把train改成dev了，train有4万多条即eval data的torch size。所以你跑dev的时候很慢。。。。你弄反了。应该是train很大，dev很小。。。。

**Comment by Ricardokevins** [comment]
--train data--
torch.Size([200, 1, 128])
torch.Size([200, 1, 128])
torch.Size([200])
--train data--
torch.Size([200, 1, 128])
torch.Size([200, 1, 128])
torch.Size([200])
--eval data--
torch.Size([45558, 1, 128])
torch.Size([45558, 1, 128])
torch.Size([45558])

如你打印的结果，train只有200，dev有45558

**Comment by cantianaishu** [comment]
十分感谢您耐心的解答，我删除了train.py以及dev.py，重新跑了一遍loader，然后运行mian，依然如下所示，然后很慢，您好是哪一步出了问题呢，我没有修改过您的代码

--train data--
torch.Size([200, 1, 128])
torch.Size([200, 1, 128])
torch.Size([200])
--train data--
torch.Size([200, 1, 128])
torch.Size([200, 1, 128])
torch.Size([200])
--eval data--
torch.Size([45558, 1, 128])
torch.Size([45558, 1, 128])
torch.Size([45558])
epoch  0  loss:  2.12479829788208 right 51 total 200 Acc: 0.255

**Comment by cantianaishu** [comment]
然后和您说一下，我的电脑是集成显卡，和此有关吗

**Comment by Ricardokevins** [comment]
> 十分感谢您耐心的解答，我删除了train.py以及dev.py，重新跑了一遍loader，然后运行mian，依然如下所示，然后很慢，您好是哪一步出了问题呢，我没有修改过您的代码
> 
> --train data-- torch.Size([200, 1, 128]) torch.Size([200, 1, 128]) torch.Size([200]) --train data-- torch.Size([200, 1, 128]) torch.Size([200, 1, 128]) torch.Size([200]) --eval data-- torch.Size([45558, 1, 128]) torch.Size([45558, 1, 128]) torch.Size([45558]) epoch 0 loss: 2.12479829788208 right 51 total 200 Acc: 0.255

你找一个loader里，我对train做了限制，只拿了200条，你可以类似的对dev进行处理，不加载全部的四万条dev数据。
我不知道你是否使用了CUDA，假设使用了CUDA，那速度肯定是很慢的。假如CUDA都没用，那肯定是更慢的。。。

**Comment by Ricardokevins** [comment]
你如果想用集成显卡跑完 完整的数据集。这几乎是不可能的。。。。要么改小数据，要么换个设备

**Comment by cantianaishu** [comment]
谢谢解答
