### ISSUE TITLE
我想问一下，dev.json文件夹里没有，我查了一下底下给的数据地址，还是没有找到，可以发一下吗

### ISSUE THREAD

**Issue by GCKt** [Ricardokevins/Bert-In-Relation-Extraction#3]

**Comment by Ricardokevins** [comment]
> _No description provided._

https://github.com/Ricardokevins/Bert-In-Relation-Extraction/issues/1

**Comment by GCKt** [comment]
> > _No description provided._
> 
> #1

博主，你昨天说的我已经弄好了，现在运行demo文件，出现RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.这个错误，想问问这是怎么回事

**Comment by Ricardokevins** [comment]
> > > _No description provided._
> > 
> > 
> > #1
> 
> 博主，你昨天说的我已经弄好了，现在运行demo文件，出现RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.这个错误，想问问这是怎么回事

因为你的电脑没有GPU，所以有问题

**Comment by GCKt** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > #1
> > 
> > 
> > 博主，你昨天说的我已经弄好了，现在运行demo文件，出现RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.这个错误，想问问这是怎么回事
> 
> 因为你的电脑没有GPU，所以有问题

好的，博主，GPU已经安好了
