### ISSUE TITLE
Precision, Recall, F-1 Score

### ISSUE THREAD

**Issue by Dimas263** [Ricardokevins/Bert-In-Relation-Extraction#30]
Sir, I'm running well my program, but I don't know how can I calculate F-1 Score?

**Comment by Ricardokevins** [comment]
> Sir, I'm running well my program, but I don't know how can I calculate F-1 Score?

Maybe You can think of entity extraction as a multi-category classification. Given Document and entity pair, model give a prediciton label. Then you can caculate F1-score or Precision Recall
