### ISSUE TITLE
预处理问题

### ISSUE THREAD

**Issue by dongzhue** [Ricardokevins/Bert-In-Relation-Extraction#31]
您好，我想请教一下为什么我按照readmem里面对训练集预处理后报错了
![image](https://user-images.githubusercontent.com/71163712/172049696-b3b2c4e2-bd68-4f20-89b0-7461cc56d968.png)
![image](https://user-images.githubusercontent.com/71163712/172049743-02854209-e43f-4a4b-a60f-9879fc633afd.png)

**Comment by Ricardokevins** [comment]
> 您好，我想请教一下为什么我按照readmem里面对训练集预处理后报错了 ![image](https://user-images.githubusercontent.com/71163712/172049696-b3b2c4e2-bd68-4f20-89b0-7461cc56d968.png) ![image](https://user-images.githubusercontent.com/71163712/172049743-02854209-e43f-4a4b-a60f-9879fc633afd.png)

可能是一些编码问题，你可以上网百度一下报错

**Comment by dongzhue** [comment]
谢谢你，我解决问题了，我把出错的那行数据给删除了居然成功了，太神奇了！

**Comment by dongzhue** [comment]
> > 您好，我想请教一下为什么我按照readmem里面对训练集预处理后报错了 ![image](https://user-images.githubusercontent.com/71163712/172049696-b3b2c4e2-bd68-4f20-89b0-7461cc56d968.png) ![image](https://user-images.githubusercontent.com/71163712/172049743-02854209-e43f-4a4b-a60f-9879fc633afd.png)
> 
> 可能是一些编码问题，你可以上网百度一下报错

谢谢你，我解决问题了，我把出错的那行数据给删除了居然成功了，太神奇了！
