### ISSUE TITLE
训练结果的一些问题

### ISSUE THREAD

**Issue by dongzhue** [Ricardokevins/Bert-In-Relation-Extraction#32]
![image](https://user-images.githubusercontent.com/71163712/172153892-3bb001c1-b75b-4691-8c0b-2894a67bdca2.png)
博主您好，我尝试用您的36w条数据+4w验证集训练了一下，这个结果算是复现了您的训练结果吗？
还有一个问题，这个报错是不是因为我服务器的空间不足了所以模型保存不了了呀

当时跑的时候
![image](https://user-images.githubusercontent.com/71163712/172154205-be3e600f-59b8-4ab3-877d-c4c111c11006.png)
当时跑的时候一直在这里卡着不动，就是这个using GPU这里，这个情况正常吗？

**Comment by Ricardokevins** [comment]
> ![image](https://user-images.githubusercontent.com/71163712/172153892-3bb001c1-b75b-4691-8c0b-2894a67bdca2.png) 博主您好，我尝试用您的36w条数据+4w验证集训练了一下，这个结果算是复现了您的训练结果吗？ 还有一个问题，这个报错是不是因为我服务器的空间不足了所以模型保存不了了呀
> 
> 当时跑的时候 ![image](https://user-images.githubusercontent.com/71163712/172154205-be3e600f-59b8-4ab3-877d-c4c111c11006.png) 当时跑的时候一直在这里卡着不动，就是这个using GPU这里，这个情况正常吗？

报错因为服务器磁盘满了，卡在using GPU可以自己调试一下看看卡在哪里

**Comment by dongzhue** [comment]
好的，我刚刚问了一下服务器管理员确实是这个问题，谢谢您
