### ISSUE TITLE
sent = ent1 + ent2+ text

### ISSUE THREAD

**Issue by sdx9078** [Ricardokevins/Bert-In-Relation-Extraction#35]
请问test.py里，为什么sent是ent1 + ent2+ text的结合，他们之后还会被分开吗，还是说作为一个sent整体进行识别了？如果是后者，那么他怎么知道要判别哪两个实体之间的关系？

**Comment by Ricardokevins** [comment]
> 请问test.py里，为什么sent是ent1 + ent2+ text的结合，他们之后还会被分开吗，还是说作为一个sent整体进行识别了？如果是后者，那么他怎么知道要判别哪两个实体之间的关系？

拼在一起，把目标实体对的信息也传进去，并希望模型可以学习到prepend在前面的这部分信息

**Comment by sdx9078** [comment]
请问如果不加上ent1 + ent2，也会有有效结果出现吗？而且是如何让模型可以学习到prepend在前面的这部分信息的呢，在代码里我看好像没有体现（我是个小白，抱歉，如果您能解答万分感激！）

**Comment by Ricardokevins** [comment]
> 请问如果不加上ent1 + ent2，也会有有效结果出现吗？而且是如何让模型可以学习到prepend在前面的这部分信息的呢，在代码里我看好像没有体现（我是个小白，抱歉，如果您能解答万分感激！）

你可以自己试试，但是理论上来说你完全不给Ent1和Ent2，模型怎么知道你要计算的实体对呢。
