### ISSUE TITLE
dev.json文件在哪里

### ISSUE THREAD

**Issue by 1225hao** [Ricardokevins/Bert-In-Relation-Extraction#36]
数据集下载链接下载的内容不对，而且json文件在哪里获取

**Comment by Ricardokevins** [comment]
> 数据集下载链接下载的内容不对，而且json文件在哪里获取

因为百度自己重新组织了页面，所以内容不对，我在readme里更新一些。
能给个Star就更好了

**Comment by Ricardokevins** [comment]
> 数据集下载链接下载的内容不对，而且json文件在哪里获取

问题已更新，没啥问题的话就关issue了

**Comment by 1225hao** [comment]
okok 已经star啦
