### ISSUE TITLE
大佬 ，运行main.py时候报错了，是格式的问题吗

### ISSUE THREAD

**Issue by 1225hao** [Ricardokevins/Bert-In-Relation-Extraction#37]
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    data=load_train()
  File "/data/xinhao/nlpCode/Bert-In-Relation-Extraction-main/loader.py", line 108, in load_train
    sent=dic['ent1']+dic['ent2']+dic['text']
TypeError:  unsupported operand type(s) for +: 'dict' and 'str'

**Comment by Ricardokevins** [comment]
> Traceback (most recent call last): File "main.py", line 64, in data=load_train() File "/data/xinhao/nlpCode/Bert-In-Relation-Extraction-main/loader.py", line 108, in load_train sent=dic['ent1']+dic['ent2']+dic['text'] TypeError: unsupported operand type(s) for +: 'dict' and 'str'

你在这个语句前加上print这三个东西，我看下输出

**Comment by 1225hao** [comment]
<img width="671" alt="截屏2022-12-07 上午12 57 32" src="https://user-images.githubusercontent.com/95691526/205974595-aee3bc84-bf32-4540-bfa3-4f277a72bd60.png">

**Comment by Ricardokevins** [comment]
> <img alt="截屏2022-12-07 上午12 57 32" width="671" src="https://user-images.githubusercontent.com/95691526/205974595-aee3bc84-bf32-4540-bfa3-4f277a72bd60.png">

print(dic['ent1'])

print(dic['ent2'])

print(dic['text'])

你是不是不会写python啊。。。

**Comment by 1225hao** [comment]
<img width="814" alt="截屏2022-12-07 上午1 03 49" src="https://user-images.githubusercontent.com/95691526/205975916-754a211f-f021-4405-8207-1f649f1dd32a.png">
让您见笑了，之前没怎么接触过python和深度学习，按照您说的输出了下。

**Comment by 1225hao** [comment]
感谢你这么耐心的帮助

**Comment by Ricardokevins** [comment]
> <img alt="截屏2022-12-07 上午1 03 49" width="814" src="https://user-images.githubusercontent.com/95691526/205975916-754a211f-f021-4405-8207-1f649f1dd32a.png">
> 
> 让您见笑了，之前没怎么接触过python和深度学习，按照您说的输出了下。

你数据集下载的不对，你打开你的train.json，然后Ctrl+F找到这一行数据 "《邪少xxxxxxxxx天下“，贴到这里我看下

**Comment by 1225hao** [comment]
ok

**Comment by 1225hao** [comment]
<img width="1170" alt="截屏2022-12-07 上午1 23 01" src="https://user-images.githubusercontent.com/95691526/205979865-ef61e9ca-902d-44ae-b2d3-a309f32f1a02.png">

**Comment by Ricardokevins** [comment]
> <img alt="截屏2022-12-07 上午1 23 01" width="1170" src="https://user-images.githubusercontent.com/95691526/205979865-ef61e9ca-902d-44ae-b2d3-a309f32f1a02.png">

你这数据哪里下载的。。。我从我readme里那个链接下载的不是这样的

**Comment by 1225hao** [comment]
不是的

**Comment by 1225hao** [comment]
https://aistudio.baidu.com/aistudio/datasetdetail/105634
<img width="1075" alt="截屏2022-12-07 上午1 26 04" src="https://user-images.githubusercontent.com/95691526/205980529-b580141d-ee79-4290-873e-0551fcd841c4.png">
当时一直打不开 您之前的链接 就自己找了这个  等回来之后看到您又给了一个链接

**Comment by Ricardokevins** [comment]
> https://aistudio.baidu.com/aistudio/datasetdetail/105634 <img alt="截屏2022-12-07 上午1 26 04" width="1075" src="https://user-images.githubusercontent.com/95691526/205980529-b580141d-ee79-4290-873e-0551fcd841c4.png"> 当时一直打不开 您之前的链接 就自己找了这个 等回来之后看到您又给了一个链接

那你可不就得按我的弄吗。。。你重新下载一个就行了

**Comment by 1225hao** [comment]
我当时大概看了一下里边内容。没有细看格式和数据类型，

**Comment by 1225hao** [comment]
嗯嗯 好嘞 ，感谢您耐心的帮助。

**Comment by Ricardokevins** [comment]
> 嗯嗯 好嘞 ，感谢您耐心的帮助。

没事，可以学下python基础的语法，还是挺有用的hhhh，不然做不下去的
