### ISSUE TITLE
demo,py问题

### ISSUE THREAD

**Issue by yys-1** [Ricardokevins/Bert-In-Relation-Extraction#38]
在demo中，直接替换test函数中保存后的.pth模型，在windows下，exit那出现问题怎么解决，非常感谢解答

**Comment by Ricardokevins** [comment]
> 在demo中，直接替换test函数中保存后的.pth模型，在windows下，exit那出现问题怎么解决，非常感谢解答

问的太含糊了，来点更详细的信息，包括修改的步骤、代码位置、报错位置、报错信息

**Comment by yys-1** [comment]
> 

没事了。感谢，已经很详细了，发现是函数名不能有test，我在windows上运行的。

**Comment by lszdhr** [comment]
您好，我没有找到pth文件😭请问是百度网盘下载的那个pth文件吗

**Comment by yys-1** [comment]
时间久了记得不清，应该是的。我项目里是一个test.pth的文件

**Comment by yys-1** [comment]
> 您好，我没有找到pth文件😭请问是百度网盘下载的那个pth文件吗

时间久了记得不清，应该是的。我项目里是一个test.pth的文件
