### ISSUE TITLE
关于transformers 2.5.1

### ISSUE THREAD

**Issue by bimintelligence** [Ricardokevins/Bert-In-Relation-Extraction#39]
您好，我尝试了conda install transformers=2.5.1
和pip install transformers==2.5.1均找不到包，有什么好的办法吗

**Comment by Ricardokevins** [comment]
> 您好，我尝试了conda install transformers=2.5.1 和pip install transformers==2.5.1均找不到包，有什么好的办法吗

不清楚，装个相近的应该就行
