### ISSUE TITLE
关于模型结构

### ISSUE THREAD

**Issue by huaxiaolu** [Ricardokevins/Bert-In-Relation-Extraction#4]
请问博主 整个模型是单独bert的应用还是bert加上其他lstm等神经网络 就是有没有那种模型的整体结构图呢？ 如果有能参考一下吗 谢谢啦

**Comment by Ricardokevins** [comment]
> 请问博主 整个模型是单独bert的应用还是bert加上其他lstm等神经网络 就是有没有那种模型的整体结构图呢？ 如果有能参考一下吗 谢谢啦

BERT+Dropout+linear，模型图可以直接print(model)查看

**Comment by huaxiaolu** [comment]
> > 请问博主 整个模型是单独bert的应用还是bert加上其他lstm等神经网络 就是有没有那种模型的整体结构图呢？ 如果有能参考一下吗 谢谢啦
> 
> BERT+Dropout+linear，模型图可以直接print(model)查看

我用print的方法查看了模型结构 ，在bert模型输出之后还有个pooler层，这个池化层的作用我在网上看好像是将词向量转变为句子向量，请问是这样理解的吗  然后我理解的模型结构 就是 使用自己的数据集对bert进行增量训练，然后正则化后通过全连接层输出关系结果  请问是这样嘛？

**Comment by Ricardokevins** [comment]
> > > 请问博主 整个模型是单独bert的应用还是bert加上其他lstm等神经网络 就是有没有那种模型的整体结构图呢？ 如果有能参考一下吗 谢谢啦
> > 
> > 
> > BERT+Dropout+linear，模型图可以直接print(model)查看
> 
> 我用print的方法查看了模型结构 ，在bert模型输出之后还有个pooler层，这个池化层的作用我在网上看好像是将词向量转变为句子向量，请问是这样理解的吗 然后我理解的模型结构 就是 使用自己的数据集对bert进行增量训练，然后正则化后通过全连接层输出关系结果 请问是这样嘛？

差不多吧，pooler或者取CLS应该差不多，通过对句子表示接MLP获取关系概率分布
