### ISSUE TITLE
gpu训练运行环境

### ISSUE THREAD

**Issue by xiaoxiaojingge** [Ricardokevins/Bert-In-Relation-Extraction#41]
您好，大佬，请问各个组件的版本是多少：
pytorch、cuda
我想尽快调试，然后跑通代码

**Comment by Ricardokevins** [comment]
> 您好，大佬，请问各个组件的版本是多少： pytorch、cuda 我想尽快调试，然后跑通代码

不记得了，但是应该问题不大
