### ISSUE TITLE
运行main.py的错误

### ISSUE THREAD

**Issue by xxxxuanji** [Ricardokevins/Bert-In-Relation-Extraction#43]
执行时提示ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. 请问要怎么处理

**Comment by Ricardokevins** [comment]
> 执行时提示ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. 请问要怎么处理

你可以提供一下报错的代码位置以及具体的log
我简单的猜测是因为你没有放好下载好的模型文件，导致模型需要在线下载，但是网络又不好没翻墙，就下载不了

**Comment by xxxxuanji** [comment]
帮我看一下吧 感谢感谢 确实是翻不了墙 然后我下载了模型 但好像还是不能检索到 还需要修改什么吗？
![QQ图片20231128141339](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/106537981/67ef5a1f-b699-440b-8ecf-ecd8dd31bae3)
![QQ图片20231128141344](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/106537981/e0cfe97b-562b-4ba4-8b23-a2603360debc)

**Comment by Ricardokevins** [comment]
> 帮我看一下吧 感谢感谢 确实是翻不了墙 然后我下载了模型 但好像还是不能检索到 还需要修改什么吗？ ![QQ图片20231128141339](https://private-user-images.githubusercontent.com/106537981/286150844-67ef5a1f-b699-440b-8ecf-ecd8dd31bae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTI0ODQsIm5iZiI6MTcwMTE1MjE4NCwicGF0aCI6Ii8xMDY1Mzc5ODEvMjg2MTUwODQ0LTY3ZWY1YTFmLWI2OTktNDQwYi04ZWNmLWVjZDhkZDMxYmFlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwNjE2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzAwNThmYjE2ODZhZDNkN2E0YTI4NGE1ZTJjZDhkNTVlZjZjZWZjNzhmN2M5ODQxMWI1YTU3YmUzMjFhOGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PRi58Xlqvmqxhe5aW1-Iiob-lX3mtCTAWUA6kM4tO6U) ![QQ图片20231128141344](https://private-user-images.githubusercontent.com/106537981/286150868-e0cfe97b-562b-4ba4-8b23-a2603360debc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTI0ODQsIm5iZiI6MTcwMTE1MjE4NCwicGF0aCI6Ii8xMDY1Mzc5ODEvMjg2MTUwODY4LWUwY2ZlOTdiLTU2MmItNGJhNC04YjIzLWEyNjAzMzYwZGViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQwNjE2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWZiYWMzNWJhODA0MDk1NDRlYmVjNWIzMWZhNGI2NTdjNmI0YTAzZWExYWM5MTEyZGYwNzRlMmU0MjdjMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JLNc1jGfsQmpuOUqrkECFVBTOC7dLOfcLHSKnbYbaAM)

from pretrain 里面要写具体的路径

**Comment by xxxxuanji** [comment]
tokenizer = BertTokenizer.from_pretrained("/home/tby/lyc/model/bert_2/Bert-In-Relation-Extraction-main/bert-base-chinese")
我是这样写的

**Comment by Ricardokevins** [comment]
> ```
> tokenizer = BertTokenizer.from_pretrained("/home/tby/lyc/model/bert_2/Bert-In-Relation-Extraction-main/bert-base-chinese")
> ```
> 
> 我是这样写的

我都看到你代码了。。。

<img width="959" alt="image" src="https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/43642508/be99eca5-d802-42f7-8460-87a1cc278a35">

**Comment by xxxxuanji** [comment]
啊！！下边的没改！感谢大佬！！
