### ISSUE TITLE
英文数据集

### ISSUE THREAD

**Issue by xxxxuanji** [Ricardokevins/Bert-In-Relation-Extraction#44]
你好 我想问一下能否修改模型为bert-base-cased，并将英文数据写入并运行，我简单改了一下模型和数据，但报错很多，能帮我看一下吗？
![QQ图片20231130163732](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/106537981/6643bca6-adf5-4202-985c-9b489938dd4f)
![QQ图片20231130163737](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/106537981/fb60bd68-c869-43dc-8cf2-09483542e491)

**Comment by xxxxuanji** [comment]
我修改了一些model中的路径就可以运行了，但训练集比较小只有4800个数据，测试集有500多 训练20epoch的正确率大概是70%这结果正常吗？

**Comment by Ricardokevins** [comment]
> 我修改了一些model中的路径就可以运行了，但训练集比较小只有4800个数据，测试集有500多 训练20epoch的正确率大概是70%这结果正常吗？

还好吧，主要还是你数据太少了，我觉得还算正常

**Comment by Violettttee** [comment]
请问如果我想用英文数据集测试的话是否只需要修改模型相关的，例如下载bert-base-cased并修改路径，替换数据集等？需要对transformer进行修改吗？

**Comment by Ricardokevins** [comment]
> 请问如果我想用英文数据集测试的话是否只需要修改模型相关的，例如下载bert-base-cased并修改路径，替换数据集等？需要对transformer进行修改吗？

不需要的

**Comment by a-vegetablebird** [comment]
> 我修改了一些model中的路径就可以运行了，但训练集比较小只有4800个数据，测试集有500多 训练20epoch的正确率大概是70%这结果正常吗？

你好，请问能给我分享一份代码吗？我也在尝试替换成bert-base-cased，但限于水平，有点困难
