### ISSUE TITLE
英文数据集训练

### ISSUE THREAD

**Issue by Violettttee** [Ricardokevins/Bert-In-Relation-Extraction#46]
如果使用英文数据集进行训练的话是否只需要修改为相应格式的英文数据集，以及将bert-base-chinese改成英文的bert模型即可？

**Comment by Ricardokevins** [comment]
> 如果使用英文数据集进行训练的话是否只需要修改为相应格式的英文数据集，以及将bert-base-chinese改成英文的bert模型即可？

是的，当然还有一些细节你可以阅读代码
