### ISSUE TITLE
train.json在代码中目前是作为测试集的吗？

### ISSUE THREAD

**Issue by Violettttee** [Ricardokevins/Bert-In-Relation-Extraction#47]
如图，
![image](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/110839053/e51b1d2f-465c-492c-afb4-84ea85088a50)
看load_train()函数这里只读取了前200个数据，请问大佬意思是train.json是作为测试集使用的吗？反而是dev.json完整的读出了所有数据。

**Comment by Violettttee** [comment]
大佬如果要完整训练的话是不是应该删除这个截取，或者将截取的片段长度变大？如果dev集有3w条数据的话，训练集用多少条数据比较合适呢？

**Comment by Ricardokevins** [comment]
> 大佬如果要完整训练的话是不是应该删除这个截取，或者将截取的片段长度变大？如果dev集有3w条数据的话，训练集用多少条数据比较合适呢？

根据你的资源来决定吧，要是硬说的话，那肯定都训练可能更好
