### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'label'

### ISSUE THREAD

**Issue by songsa1** [Ricardokevins/Bert-In-Relation-Extraction#5]
请问可以提供一下环境依赖吗，我按照您给的依赖：pytorch=1.5.1 transformers=2.5.1
可以正常训练模型，但是在模型测试执行demo.py时总是会报错：
![image](https://user-images.githubusercontent.com/42863413/111134483-a2fd8d80-85b6-11eb-8cbb-2967af452a2c.png)
这是我的环境依赖
![image](https://user-images.githubusercontent.com/42863413/111134626-c1fc1f80-85b6-11eb-89eb-da7aec53664e.png)

望回复，谢谢

**Comment by Ricardokevins** [comment]
> 请问可以提供一下环境依赖吗，我按照您给的依赖：pytorch=1.5.1 transformers=2.5.1
> 可以正常训练模型，但是在模型测试执行demo.py时总是会报错：
> ![image](https://user-images.githubusercontent.com/42863413/111134483-a2fd8d80-85b6-11eb-8cbb-2967af452a2c.png)
> 这是我的环境依赖
> ![image](https://user-images.githubusercontent.com/42863413/111134626-c1fc1f80-85b6-11eb-89eb-da7aec53664e.png)
> 
> 望回复，谢谢

哦哦，这个主要是我不久之前重写了模型，然后demo里没有做对应的修改，导致了缺失一个参数，我现在改了一下，你可以再试试。至于版本可以参考这个issue https://github.com/Ricardokevins/Bert-In-Relation-Extraction/issues/2

**Comment by songsa1** [comment]
> > 请问可以提供一下环境依赖吗，我按照您给的依赖：pytorch = 1.5.1 transformers = 2.5.1
> > 可以正常训练模型，但是在模型测试执行demo.py时总是会报错：
> > 这是我的环境依赖
> > ![图像](https://user-images.githubusercontent.com/42863413/111134483-a2fd8d80-85b6-11eb-8cbb-2967af452a2c.png)
> > ![图像](https://user-images.githubusercontent.com/42863413/111134626-c1fc1f80-85b6-11eb-89eb-da7aec53664e.png)
> > 望回复，谢谢
> 
> 哦哦，这个主要是我不久之前重写了模型，然后demo里没有做对应的修改，导致了缺失一个参数，我现在改了一下，你可以再试试。至于版本可以参考这个问题[＃2](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/issues/2)

您好 我重新拉了您的代码，但还是有这个问题，
![image](https://user-images.githubusercontent.com/42863413/111138289-b9a5e380-85ba-11eb-9337-c1b9f33f6807.png)
这是demo.py中导致异常的地方
![image](https://user-images.githubusercontent.com/42863413/111138417-dc37fc80-85ba-11eb-821c-32539995229e.png)

**Comment by Ricardokevins** [comment]
> > > 请问可以提供一下环境依赖吗，我按照您给的依赖：pytorch = 1.5.1 transformers = 2.5.1
> > > 可以正常训练模型，但是在模型测试执行demo.py时总是会报错：
> > > 这是我的环境依赖
> > > ![图像](https://user-images.githubusercontent.com/42863413/111134483-a2fd8d80-85b6-11eb-8cbb-2967af452a2c.png)
> > > ![图像](https://user-images.githubusercontent.com/42863413/111134626-c1fc1f80-85b6-11eb-89eb-da7aec53664e.png)
> > > 望回复，谢谢
> > 
> > 
> > 哦哦，这个主要是我不久之前重写了模型，然后demo里没有做对应的修改，导致了缺失一个参数，我现在改了一下，你可以再试试。至于版本可以参考这个问题[＃2](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/issues/2)
> 
> 您好 我重新拉了您的代码，但还是有这个问题，
> ![image](https://user-images.githubusercontent.com/42863413/111138289-b9a5e380-85ba-11eb-9337-c1b9f33f6807.png)
> 这是demo.py中导致异常的地方
> ![image](https://user-images.githubusercontent.com/42863413/111138417-dc37fc80-85ba-11eb-821c-32539995229e.png)

抱歉。。。我又改了一下，这个主要就是model定义和使用的时候回forward函数不匹配，我已经又改了一下。因为我现在的工作环境和当时运行这个代码的环境不一样，所以我本地没有进行调试（我本地的transformer是3.5.1的，跑不了这个代码，没法复现问题），你可以再试试

**Comment by Ricardokevins** [comment]
现在应该可以运行了，我重新在本地简单的train了一个模型，load之后我看到demo可以正常的使用

**Comment by songsa1** [comment]
> 现在应该可以运行了，我重新在本地简单的train了一个模型，load之后我看到demo可以正常的使用

您好 我刚刚重新拉了一份代码试了试，我在保证transformers=2.5.1 和torch=1.5.1的前提下，将您留的train.json复制了一份当作dev.json 然后依旧可以正常的训练模型，但是在demo.py中的test方法依旧报错，这是异常log。麻烦您看下
![image](https://user-images.githubusercontent.com/42863413/111243405-fe259380-863b-11eb-97fb-b1f47888382f.png)

您说您demo可以正常使用，是因为我的dev.json是从train.json复制来的原因吗？又或者是我的某个依赖不对呢
望回复

**Comment by songsa1** [comment]
> > 现在应该可以运行了，我重新在本地简单的train了一个模型，load之后我看到demo可以正常的使用
> 
> 您好 我刚刚重新拉了一份代码试了试，我在保证transformers=2.5.1 和torch=1.5.1的前提下，将您留的train.json复制了一份当作dev.json 然后依旧可以正常的训练模型，但是在demo.py中的test方法依旧报错，这是异常log。麻烦您看下
> ![image](https://user-images.githubusercontent.com/42863413/111243405-fe259380-863b-11eb-97fb-b1f47888382f.png)
> 
> 您说您demo可以正常使用，是因为我的dev.json是从train.json复制来的原因吗？又或者是我的某个依赖不对呢
> 望回复
我刚刚看了下啊，是不是您这个下标写的稍微有点问题，是否应该是这个：
![image](https://user-images.githubusercontent.com/42863413/111244512-0979be80-863e-11eb-86d7-ff38f2fb81be.png)

**Comment by Ricardokevins** [comment]
> > > 现在应该可以运行了，我重新在本地简单的train了一个模型，load之后我看到demo可以正常的使用
> > 
> > 
> > 您好 我刚刚重新拉了一份代码试了试，我在保证transformers=2.5.1 和torch=1.5.1的前提下，将您留的train.json复制了一份当作dev.json 然后依旧可以正常的训练模型，但是在demo.py中的test方法依旧报错，这是异常log。麻烦您看下
> > ![image](https://user-images.githubusercontent.com/42863413/111243405-fe259380-863b-11eb-97fb-b1f47888382f.png)
> > 您说您demo可以正常使用，是因为我的dev.json是从train.json复制来的原因吗？又或者是我的某个依赖不对呢
> > 望回复
> > 我刚刚看了下啊，是不是您这个下标写的稍微有点问题，是否应该是这个：
> > ![image](https://user-images.githubusercontent.com/42863413/111244512-0979be80-863e-11eb-86d7-ff38f2fb81be.png)

感谢指出，好像是这个原因，我commit了修改
