### ISSUE TITLE
gpu/cpu?

### ISSUE THREAD

**Issue by Allisonparkkkking** [Ricardokevins/Bert-In-Relation-Extraction#50]
博主你好，我下载的是cpu版的pytorch，运行报错：raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.想问一下这个程序是只支持gpu环境吗

**Comment by Ricardokevins** [comment]
> 博主你好，我下载的是cpu版的pytorch，运行报错：raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.想问一下这个程序是只支持gpu环境吗

回答：
1. 我默认是有GPU的，可以改成只用cpu
2. 用下搜索引擎来学习和解决问题。我后面可能不会再回答这类问题了

**Comment by Ricardokevins** [comment]
<img width="1310" alt="image" src="https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/43642508/cd672273-a9ae-44a3-82ab-5331602adaad">

**Comment by Allisonparkkkking** [comment]
好的ww
