### ISSUE TITLE
这个模型可以无监督学习吗

### ISSUE THREAD

**Issue by 226gemma** [Ricardokevins/Bert-In-Relation-Extraction#51]
输入所有关系感觉需要耗费很多人力，可以由模型自己识别吗？应该怎么改一下呢？

**Comment by Ricardokevins** [comment]
> 输入所有关系感觉需要耗费很多人力，可以由模型自己识别吗？应该怎么改一下呢？

没有太理解你这里说的“输入所有关系”是什么意思

一般来说需要有预定义的关系类别，以及对应的数据，模型才能有针对性的学习“什么样的上下文表达了什么样的关系”

可能最新的一些工作可以解决你的问题，但是我很久不做和了解相关方面了，你可以查询其他的资料来解决你的问题
