### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by TokaiTeio3** [Ricardokevins/Bert-In-Relation-Extraction#56]
![image](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/115518004/fb17af24-c6c6-449f-9efb-47770619272e)
作者您好，我有两个问题：1是我在huggingface上找到bert-base-chinese库（如上图），请问具体需要哪些文件呢？
2是我使用了自己的数据，但是在加载模型时出现了以下（如下图）问题，请问您有解决的方法吗？
![image](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/115518004/bbdf6f05-4c86-4db3-9ce5-e3f64ac2b19f)

**Comment by TokaiTeio3** [comment]
我对加载数据的代码进行了一定的修改，如下:
![image](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/115518004/fdd708bd-73ea-4230-9337-6967ca4a3553)

**Comment by Ricardokevins** [comment]
> ![image](https://private-user-images.githubusercontent.com/115518004/333182859-fb17af24-c6c6-449f-9efb-47770619272e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Njg1NzIsIm5iZiI6MTcxNjQ2ODI3MiwicGF0aCI6Ii8xMTU1MTgwMDQvMzMzMTgyODU5LWZiMTdhZjI0LWM2YzYtNDQ5Zi05ZWZiLTQ3NzcwNjE5MjcyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMjQ0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDU1NmE3MTJlNDNlZGYwMmExYTE1ZjhiMjU1OWExNzY5MzA2MGYwYzc5MmRmYTgzMjFlNmM1OTJkMDBjNTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yyYkA5kfvcPiodRxxvHeA9essA1s2pb2pmuv8fhdFNM) 作者您好，我有两个问题：1是我在huggingface上找到bert-base-chinese库（如上图），请问具体需要哪些文件呢？ 2是我使用了自己的数据，但是在加载模型时出现了以下（如下图）问题，请问您有解决的方法吗？ ![image](https://private-user-images.githubusercontent.com/115518004/333183998-bbdf6f05-4c86-4db3-9ce5-e3f64ac2b19f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Njg1NzIsIm5iZiI6MTcxNjQ2ODI3MiwicGF0aCI6Ii8xMTU1MTgwMDQvMzMzMTgzOTk4LWJiZGY2ZjA1LTRjODYtNGRiMy05Y2U1LWUzZjY0YWMyYjE5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxMjQ0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzVlZDhlYTRmZjAyMjZkMzgyODhlMTc1NjM4MmQ1YjdjYTI5MTMyMGMwZDc2YjVkYjRmNDM1ZGE2ODNlZjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pBC2Nwpkj17fA-kxEyxPPnyPTNjoLNV81f_uH-fGUVs)

全部下载（除了那几个400M的文件，只要下载其中pytorch_model.bin"

第二部分的报错可能和数组越界有关，你需要检查的你模型的类别以及最终标签的类别是否对应

**Comment by TokaiTeio3** [comment]
我的标签一共有两类如下图
![image](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/115518004/3d6ae96f-44eb-431f-8a22-199cdcf4e46c)
然后我的数据集合里面的话是有三种标签，“时序""因果""无"，但是我看loader中对于标签越界有处理呀
![image](https://github.com/Ricardokevins/Bert-In-Relation-Extraction/assets/115518004/2f6c34e5-ba6f-4194-9555-5a74f345cf21)
难道是我的数据太多了？

**Comment by shenglve666** [comment]
![issue1](https://github.com/user-attachments/assets/9d50bca0-85ae-42ed-8ef9-66c22f4d7f75)
你好，请问一下你下载bert-base-chinese库后，是不是直接将这些文件直接复制到项目里？我这样会报错

**Comment by Ricardokevins** [comment]
> ![issue1](https://private-user-images.githubusercontent.com/87404025/384833620-9d50bca0-85ae-42ed-8ef9-66c22f4d7f75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTQxMDQsIm5iZiI6MTczMTkxMzgwNCwicGF0aCI6Ii84NzQwNDAyNS8zODQ4MzM2MjAtOWQ1MGJjYTAtODVhZS00MmVkLThlZjktNjZjMjJmNGQ3Zjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA3MTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZDJkM2Q2NjM4YTQxYmQ4Zjg2Y2NlZjI4MTRiZGE0N2U5N2Y4YjBmZTAwM2RjMjI5OTE2NDllYjQ3MWI4YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Phv1hvCdlyRa764Ig3Qa-NXUY6rbduah8gbHjNlD1nk) 你好，请问一下你下载bert-base-chinese库后，是不是直接将这些文件直接复制到项目里？我这样会报错

什么错误呢

**Comment by shenglve666** [comment]
> > ![issue1](https://private-user-images.githubusercontent.com/87404025/384833620-9d50bca0-85ae-42ed-8ef9-66c22f4d7f75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTQxMDQsIm5iZiI6MTczMTkxMzgwNCwicGF0aCI6Ii84NzQwNDAyNS8zODQ4MzM2MjAtOWQ1MGJjYTAtODVhZS00MmVkLThlZjktNjZjMjJmNGQ3Zjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA3MTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZDJkM2Q2NjM4YTQxYmQ4Zjg2Y2NlZjI4MTRiZGE0N2U5N2Y4YjBmZTAwM2RjMjI5OTE2NDllYjQ3MWI4YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Phv1hvCdlyRa764Ig3Qa-NXUY6rbduah8gbHjNlD1nk) 你好，请问一下你下载bert-base-chinese库后，是不是直接将这些文件直接复制到项目里？我这样会报错
> 
> 什么错误呢

已经解决了。1.把bert-base-chinese库里的东西都下载复制到项目中。2.原项目中的相对地址格式'/bert-base-chinese'需要改成'./bert-base-chinese'
