### ISSUE TITLE
请问怎么用自己的数据做关系抽取?

### ISSUE THREAD

**Issue by mading0817** [Ricardokevins/Bert-In-Relation-Extraction#6]
很高的准确率! 非常期待可以试试.
我现在已经实现了NER, 也有很多自己的数据, 现在先通过自己的NER和文本数据做关系抽取, 怎么应该怎么实现啊?

**Comment by Ricardokevins** [comment]
> 很高的准确率! 非常期待可以试试.
> 我现在已经实现了NER, 也有很多自己的数据, 现在先通过自己的NER和文本数据做关系抽取, 怎么应该怎么实现啊?

方法1：阅读代码关于数据载入的部分 （loader.py)，自定义数据的读取
方法2：先用脚本处理自己的数据为README里的格式，然后运行

**Comment by mading0817** [comment]
好的! 多谢啦
这个项目您还准备继续维护吗?

**Comment by Ricardokevins** [comment]
> 好的! 多谢啦
> 这个项目您还准备继续维护吗?

昂，这个项目就有BUG修BUG，没BUG的话应该不会添加新的Feature了，因为我不是作关系抽取这个方向的。
最近维护的一些新的好玩的NLP项目在另一个库里：https://github.com/Ricardokevins/Kevinpro-NLP-demo
哈哈哈

**Comment by mading0817** [comment]
好的好的, 十分感谢

**Comment by mading0817** [comment]
因为我还没有仔细阅读您的代码, 所以想问一下:
我准备按您方法2进行尝试:
同时我还需要做的是把这个也自定义下:
id2rel={0: 'UNK', 1: '主演', 2: '歌手', 3: '简称', 4: '总部地点', 5: '导演', 
        6: '出生地', 7: '目', 8: '出生日期', 9: '占地面积', 10: '上映时间',
        11: '出版社', 12: '作者', 13: '号', 14: '父亲', 15: '毕业院校', 
        16: '成立日期', 17: '改编自', 18: '主持人', 19: '所属专辑', 
        20: '连载网站', 21: '作词', 22: '作曲', 23: '创始人', 24: '丈夫', 
        25: '妻子', 26: '朝代', 27: '民族', 28: '国籍', 29: '身高', 30: '出品公司', 
        31: '母亲', 32: '编剧', 33: '首都', 34: '面积', 35: '祖籍', 36: '嘉宾', 
        37: '字', 38: '海拔', 39: '注册资本', 40: '制片人', 41: '董事长', 42: '所在城市',
        43: '气候', 44: '人口数量', 45: '邮政编码', 46: '主角', 47: '官方语言', 48: '修业年限'}  

然后我把自己的数据按照readerme组织好送去训练
预测的时候大概的流程是先把文本内容做实体识别, 然后送一段文本进去, 就可以预测出该文本中实体与实体之间的关系了吗?
可以看到预测的概率等这些嘛?还有没有啥需要我自己改的或者手调啥的?
谢谢啦

**Comment by Ricardokevins** [comment]
> 因为我还没有仔细阅读您的代码, 所以想问一下:
> 我准备按您方法2进行尝试:
> 同时我还需要做的是把这个也自定义下:
> id2rel={0: 'UNK', 1: '主演', 2: '歌手', 3: '简称', 4: '总部地点', 5: '导演',
> 6: '出生地', 7: '目', 8: '出生日期', 9: '占地面积', 10: '上映时间',
> 11: '出版社', 12: '作者', 13: '号', 14: '父亲', 15: '毕业院校',
> 16: '成立日期', 17: '改编自', 18: '主持人', 19: '所属专辑',
> 20: '连载网站', 21: '作词', 22: '作曲', 23: '创始人', 24: '丈夫',
> 25: '妻子', 26: '朝代', 27: '民族', 28: '国籍', 29: '身高', 30: '出品公司',
> 31: '母亲', 32: '编剧', 33: '首都', 34: '面积', 35: '祖籍', 36: '嘉宾',
> 37: '字', 38: '海拔', 39: '注册资本', 40: '制片人', 41: '董事长', 42: '所在城市',
> 43: '气候', 44: '人口数量', 45: '邮政编码', 46: '主角', 47: '官方语言', 48: '修业年限'}
> 
> 然后我把自己的数据按照readerme组织好送去训练
> 预测的时候大概的流程是先把文本内容做实体识别, 然后送一段文本进去, 就可以预测出该文本中实体与实体之间的关系了吗?
> 可以看到预测的概率等这些嘛?还有没有啥需要我自己改的或者手调啥的?
> 谢谢啦

差不多，这个模型就是把 实体对 + 句子输入，然后输出对应的类别。模型会输出概率。
