### ISSUE TITLE
在运行mian.py时报错

### ISSUE THREAD

**Issue by LiAI-tech** [Ricardokevins/Bert-In-Relation-Extraction#8]

**Comment by Ricardokevins** [comment]
?具体报的啥错啊。。。

**Comment by Ricardokevins** [comment]
> _No description provided._

?具体报的啥错啊。。。

**Comment by Ricardokevins** [comment]
> _No description provided._

看你邮件里的描述，应该是文件错误，没有成功加载数据，所以转tensor的时候报了nonetype
