### ISSUE TITLE
语言

### ISSUE THREAD

**Issue by lingling1992** [Ricardokevins/Bert-In-Relation-Extraction#9]
您好，可以使用别的语言训练模型吗？别的语言关系抽取准确率怎么样呢

**Comment by Ricardokevins** [comment]
> 您好，可以使用别的语言训练模型吗？别的语言关系抽取准确率怎么样呢

当然可以了，我是在中文环境下做的，你可以用各种语言做都可以。
做法就是修改预训练模型的类型，以及修改tokenizer就可以了

**Comment by lingling1992** [comment]
![image](https://user-images.githubusercontent.com/46208343/145773418-ddac8006-3b30-4065-acff-328774367261.png)
训练数据不是2万吗？这儿写的200，我改成2000之后
![image](https://user-images.githubusercontent.com/46208343/145773522-dfe3b1c2-5723-47c0-9ac8-1b8cfdd18fd3.png)
报错了

**Comment by Ricardokevins** [comment]
> ![image](https://user-images.githubusercontent.com/46208343/145773418-ddac8006-3b30-4065-acff-328774367261.png) 训练数据不是2万吗？这儿写的200，我改成2000之后 ![image](https://user-images.githubusercontent.com/46208343/145773522-dfe3b1c2-5723-47c0-9ac8-1b8cfdd18fd3.png) 报错了

检查json文件的格式，这个和数量没啥关系

**Comment by lingling1992** [comment]
3000个都对，一上万就报错了

**Comment by Ricardokevins** [comment]
> 3000个都对，一上万就报错了

你可以输出line来确定错误位置的格式
